/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 2.10.3
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.AccionsEstatsBDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.Comentaris;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.DropdownItemBDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * CanviEstatMassiuRDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-11-08T15:53:07.446+01:00")
public class CanviEstatMassiuRDTO {
  @JsonProperty("codiUnitatGestora")
  private String codiUnitatGestora = null;

  @JsonProperty("codiUnitatGestoraConvidadaList")
  private List<String> codiUnitatGestoraConvidadaList = null;

  @JsonProperty("comentari")
  private Comentaris comentari = null;

  @JsonProperty("dataLimitAllegacio")
  private DateTime dataLimitAllegacio = null;

  @JsonProperty("dataLimitRequeriment")
  private DateTime dataLimitRequeriment = null;

  @JsonProperty("estatActual")
  private DropdownItemBDTO estatActual = null;

  @JsonProperty("estatAnterior")
  private DropdownItemBDTO estatAnterior = null;

  @JsonProperty("estatFuturo")
  private DropdownItemBDTO estatFuturo = null;

  @JsonProperty("idAccioEstat")
  private BigDecimal idAccioEstat = null;

  @JsonProperty("idExpedientsList")
  private List<BigDecimal> idExpedientsList = null;

  @JsonProperty("tancamentAutomatic")
  private Integer tancamentAutomatic = null;

  @JsonProperty("transicionsPosibles")
  private List<AccionsEstatsBDTO> transicionsPosibles = null;

  public CanviEstatMassiuRDTO codiUnitatGestora(String codiUnitatGestora) {
    this.codiUnitatGestora = codiUnitatGestora;
    return this;
  }

   /**
   * Get codiUnitatGestora
   * @return codiUnitatGestora
  **/
  @ApiModelProperty(value = "")
  public String getCodiUnitatGestora() {
    return codiUnitatGestora;
  }

  public void setCodiUnitatGestora(String codiUnitatGestora) {
    this.codiUnitatGestora = codiUnitatGestora;
  }

  public CanviEstatMassiuRDTO codiUnitatGestoraConvidadaList(List<String> codiUnitatGestoraConvidadaList) {
    this.codiUnitatGestoraConvidadaList = codiUnitatGestoraConvidadaList;
    return this;
  }

  public CanviEstatMassiuRDTO addCodiUnitatGestoraConvidadaListItem(String codiUnitatGestoraConvidadaListItem) {
    if (this.codiUnitatGestoraConvidadaList == null) {
      this.codiUnitatGestoraConvidadaList = new ArrayList<String>();
    }
    this.codiUnitatGestoraConvidadaList.add(codiUnitatGestoraConvidadaListItem);
    return this;
  }

   /**
   * Get codiUnitatGestoraConvidadaList
   * @return codiUnitatGestoraConvidadaList
  **/
  @ApiModelProperty(value = "")
  public List<String> getCodiUnitatGestoraConvidadaList() {
    return codiUnitatGestoraConvidadaList;
  }

  public void setCodiUnitatGestoraConvidadaList(List<String> codiUnitatGestoraConvidadaList) {
    this.codiUnitatGestoraConvidadaList = codiUnitatGestoraConvidadaList;
  }

  public CanviEstatMassiuRDTO comentari(Comentaris comentari) {
    this.comentari = comentari;
    return this;
  }

   /**
   * Get comentari
   * @return comentari
  **/
  @ApiModelProperty(value = "")
  public Comentaris getComentari() {
    return comentari;
  }

  public void setComentari(Comentaris comentari) {
    this.comentari = comentari;
  }

  public CanviEstatMassiuRDTO dataLimitAllegacio(DateTime dataLimitAllegacio) {
    this.dataLimitAllegacio = dataLimitAllegacio;
    return this;
  }

   /**
   * Get dataLimitAllegacio
   * @return dataLimitAllegacio
  **/
  @ApiModelProperty(value = "")
  public DateTime getDataLimitAllegacio() {
    return dataLimitAllegacio;
  }

  public void setDataLimitAllegacio(DateTime dataLimitAllegacio) {
    this.dataLimitAllegacio = dataLimitAllegacio;
  }

  public CanviEstatMassiuRDTO dataLimitRequeriment(DateTime dataLimitRequeriment) {
    this.dataLimitRequeriment = dataLimitRequeriment;
    return this;
  }

   /**
   * Get dataLimitRequeriment
   * @return dataLimitRequeriment
  **/
  @ApiModelProperty(value = "")
  public DateTime getDataLimitRequeriment() {
    return dataLimitRequeriment;
  }

  public void setDataLimitRequeriment(DateTime dataLimitRequeriment) {
    this.dataLimitRequeriment = dataLimitRequeriment;
  }

  public CanviEstatMassiuRDTO estatActual(DropdownItemBDTO estatActual) {
    this.estatActual = estatActual;
    return this;
  }

   /**
   * Get estatActual
   * @return estatActual
  **/
  @ApiModelProperty(value = "")
  public DropdownItemBDTO getEstatActual() {
    return estatActual;
  }

  public void setEstatActual(DropdownItemBDTO estatActual) {
    this.estatActual = estatActual;
  }

  public CanviEstatMassiuRDTO estatAnterior(DropdownItemBDTO estatAnterior) {
    this.estatAnterior = estatAnterior;
    return this;
  }

   /**
   * Get estatAnterior
   * @return estatAnterior
  **/
  @ApiModelProperty(value = "")
  public DropdownItemBDTO getEstatAnterior() {
    return estatAnterior;
  }

  public void setEstatAnterior(DropdownItemBDTO estatAnterior) {
    this.estatAnterior = estatAnterior;
  }

  public CanviEstatMassiuRDTO estatFuturo(DropdownItemBDTO estatFuturo) {
    this.estatFuturo = estatFuturo;
    return this;
  }

   /**
   * Get estatFuturo
   * @return estatFuturo
  **/
  @ApiModelProperty(value = "")
  public DropdownItemBDTO getEstatFuturo() {
    return estatFuturo;
  }

  public void setEstatFuturo(DropdownItemBDTO estatFuturo) {
    this.estatFuturo = estatFuturo;
  }

  public CanviEstatMassiuRDTO idAccioEstat(BigDecimal idAccioEstat) {
    this.idAccioEstat = idAccioEstat;
    return this;
  }

   /**
   * Get idAccioEstat
   * @return idAccioEstat
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getIdAccioEstat() {
    return idAccioEstat;
  }

  public void setIdAccioEstat(BigDecimal idAccioEstat) {
    this.idAccioEstat = idAccioEstat;
  }

  public CanviEstatMassiuRDTO idExpedientsList(List<BigDecimal> idExpedientsList) {
    this.idExpedientsList = idExpedientsList;
    return this;
  }

  public CanviEstatMassiuRDTO addIdExpedientsListItem(BigDecimal idExpedientsListItem) {
    if (this.idExpedientsList == null) {
      this.idExpedientsList = new ArrayList<BigDecimal>();
    }
    this.idExpedientsList.add(idExpedientsListItem);
    return this;
  }

   /**
   * Get idExpedientsList
   * @return idExpedientsList
  **/
  @ApiModelProperty(value = "")
  public List<BigDecimal> getIdExpedientsList() {
    return idExpedientsList;
  }

  public void setIdExpedientsList(List<BigDecimal> idExpedientsList) {
    this.idExpedientsList = idExpedientsList;
  }

  public CanviEstatMassiuRDTO tancamentAutomatic(Integer tancamentAutomatic) {
    this.tancamentAutomatic = tancamentAutomatic;
    return this;
  }

   /**
   * Get tancamentAutomatic
   * @return tancamentAutomatic
  **/
  @ApiModelProperty(value = "")
  public Integer getTancamentAutomatic() {
    return tancamentAutomatic;
  }

  public void setTancamentAutomatic(Integer tancamentAutomatic) {
    this.tancamentAutomatic = tancamentAutomatic;
  }

  public CanviEstatMassiuRDTO transicionsPosibles(List<AccionsEstatsBDTO> transicionsPosibles) {
    this.transicionsPosibles = transicionsPosibles;
    return this;
  }

  public CanviEstatMassiuRDTO addTransicionsPosiblesItem(AccionsEstatsBDTO transicionsPosiblesItem) {
    if (this.transicionsPosibles == null) {
      this.transicionsPosibles = new ArrayList<AccionsEstatsBDTO>();
    }
    this.transicionsPosibles.add(transicionsPosiblesItem);
    return this;
  }

   /**
   * Get transicionsPosibles
   * @return transicionsPosibles
  **/
  @ApiModelProperty(value = "")
  public List<AccionsEstatsBDTO> getTransicionsPosibles() {
    return transicionsPosibles;
  }

  public void setTransicionsPosibles(List<AccionsEstatsBDTO> transicionsPosibles) {
    this.transicionsPosibles = transicionsPosibles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CanviEstatMassiuRDTO canviEstatMassiuRDTO = (CanviEstatMassiuRDTO) o;
    return Objects.equals(this.codiUnitatGestora, canviEstatMassiuRDTO.codiUnitatGestora) &&
        Objects.equals(this.codiUnitatGestoraConvidadaList, canviEstatMassiuRDTO.codiUnitatGestoraConvidadaList) &&
        Objects.equals(this.comentari, canviEstatMassiuRDTO.comentari) &&
        Objects.equals(this.dataLimitAllegacio, canviEstatMassiuRDTO.dataLimitAllegacio) &&
        Objects.equals(this.dataLimitRequeriment, canviEstatMassiuRDTO.dataLimitRequeriment) &&
        Objects.equals(this.estatActual, canviEstatMassiuRDTO.estatActual) &&
        Objects.equals(this.estatAnterior, canviEstatMassiuRDTO.estatAnterior) &&
        Objects.equals(this.estatFuturo, canviEstatMassiuRDTO.estatFuturo) &&
        Objects.equals(this.idAccioEstat, canviEstatMassiuRDTO.idAccioEstat) &&
        Objects.equals(this.idExpedientsList, canviEstatMassiuRDTO.idExpedientsList) &&
        Objects.equals(this.tancamentAutomatic, canviEstatMassiuRDTO.tancamentAutomatic) &&
        Objects.equals(this.transicionsPosibles, canviEstatMassiuRDTO.transicionsPosibles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiUnitatGestora, codiUnitatGestoraConvidadaList, comentari, dataLimitAllegacio, dataLimitRequeriment, estatActual, estatAnterior, estatFuturo, idAccioEstat, idExpedientsList, tancamentAutomatic, transicionsPosibles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CanviEstatMassiuRDTO {\n");
    
    sb.append("    codiUnitatGestora: ").append(toIndentedString(codiUnitatGestora)).append("\n");
    sb.append("    codiUnitatGestoraConvidadaList: ").append(toIndentedString(codiUnitatGestoraConvidadaList)).append("\n");
    sb.append("    comentari: ").append(toIndentedString(comentari)).append("\n");
    sb.append("    dataLimitAllegacio: ").append(toIndentedString(dataLimitAllegacio)).append("\n");
    sb.append("    dataLimitRequeriment: ").append(toIndentedString(dataLimitRequeriment)).append("\n");
    sb.append("    estatActual: ").append(toIndentedString(estatActual)).append("\n");
    sb.append("    estatAnterior: ").append(toIndentedString(estatAnterior)).append("\n");
    sb.append("    estatFuturo: ").append(toIndentedString(estatFuturo)).append("\n");
    sb.append("    idAccioEstat: ").append(toIndentedString(idAccioEstat)).append("\n");
    sb.append("    idExpedientsList: ").append(toIndentedString(idExpedientsList)).append("\n");
    sb.append("    tancamentAutomatic: ").append(toIndentedString(tancamentAutomatic)).append("\n");
    sb.append("    transicionsPosibles: ").append(toIndentedString(transicionsPosibles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

