/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 2.10.3
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.ItemsBDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * DadesOperacionsDadesBDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-11-08T15:53:07.446+01:00")
public class DadesOperacionsDadesBDTO {
  @JsonProperty("codi")
  private String codi = null;

  @JsonProperty("grup")
  private BigDecimal grup = null;

  @JsonProperty("id")
  private BigDecimal id = null;

  @JsonProperty("idDefinicioGrup")
  private BigDecimal idDefinicioGrup = null;

  @JsonProperty("itemsList")
  private List<ItemsBDTO> itemsList = null;

  @JsonProperty("ordre")
  private Integer ordre = null;

  @JsonProperty("tipus")
  private BigDecimal tipus = null;

  @JsonProperty("titol")
  private String titol = null;

  @JsonProperty("valor")
  private String valor = null;

  public DadesOperacionsDadesBDTO codi(String codi) {
    this.codi = codi;
    return this;
  }

   /**
   * Get codi
   * @return codi
  **/
  @ApiModelProperty(value = "")
  public String getCodi() {
    return codi;
  }

  public void setCodi(String codi) {
    this.codi = codi;
  }

  public DadesOperacionsDadesBDTO grup(BigDecimal grup) {
    this.grup = grup;
    return this;
  }

   /**
   * Get grup
   * @return grup
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getGrup() {
    return grup;
  }

  public void setGrup(BigDecimal grup) {
    this.grup = grup;
  }

  public DadesOperacionsDadesBDTO id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public DadesOperacionsDadesBDTO idDefinicioGrup(BigDecimal idDefinicioGrup) {
    this.idDefinicioGrup = idDefinicioGrup;
    return this;
  }

   /**
   * Get idDefinicioGrup
   * @return idDefinicioGrup
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getIdDefinicioGrup() {
    return idDefinicioGrup;
  }

  public void setIdDefinicioGrup(BigDecimal idDefinicioGrup) {
    this.idDefinicioGrup = idDefinicioGrup;
  }

  public DadesOperacionsDadesBDTO itemsList(List<ItemsBDTO> itemsList) {
    this.itemsList = itemsList;
    return this;
  }

  public DadesOperacionsDadesBDTO addItemsListItem(ItemsBDTO itemsListItem) {
    if (this.itemsList == null) {
      this.itemsList = new ArrayList<ItemsBDTO>();
    }
    this.itemsList.add(itemsListItem);
    return this;
  }

   /**
   * Get itemsList
   * @return itemsList
  **/
  @ApiModelProperty(value = "")
  public List<ItemsBDTO> getItemsList() {
    return itemsList;
  }

  public void setItemsList(List<ItemsBDTO> itemsList) {
    this.itemsList = itemsList;
  }

  public DadesOperacionsDadesBDTO ordre(Integer ordre) {
    this.ordre = ordre;
    return this;
  }

   /**
   * Get ordre
   * @return ordre
  **/
  @ApiModelProperty(value = "")
  public Integer getOrdre() {
    return ordre;
  }

  public void setOrdre(Integer ordre) {
    this.ordre = ordre;
  }

  public DadesOperacionsDadesBDTO tipus(BigDecimal tipus) {
    this.tipus = tipus;
    return this;
  }

   /**
   * Get tipus
   * @return tipus
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTipus() {
    return tipus;
  }

  public void setTipus(BigDecimal tipus) {
    this.tipus = tipus;
  }

  public DadesOperacionsDadesBDTO titol(String titol) {
    this.titol = titol;
    return this;
  }

   /**
   * Get titol
   * @return titol
  **/
  @ApiModelProperty(value = "")
  public String getTitol() {
    return titol;
  }

  public void setTitol(String titol) {
    this.titol = titol;
  }

  public DadesOperacionsDadesBDTO valor(String valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  @ApiModelProperty(value = "")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadesOperacionsDadesBDTO dadesOperacionsDadesBDTO = (DadesOperacionsDadesBDTO) o;
    return Objects.equals(this.codi, dadesOperacionsDadesBDTO.codi) &&
        Objects.equals(this.grup, dadesOperacionsDadesBDTO.grup) &&
        Objects.equals(this.id, dadesOperacionsDadesBDTO.id) &&
        Objects.equals(this.idDefinicioGrup, dadesOperacionsDadesBDTO.idDefinicioGrup) &&
        Objects.equals(this.itemsList, dadesOperacionsDadesBDTO.itemsList) &&
        Objects.equals(this.ordre, dadesOperacionsDadesBDTO.ordre) &&
        Objects.equals(this.tipus, dadesOperacionsDadesBDTO.tipus) &&
        Objects.equals(this.titol, dadesOperacionsDadesBDTO.titol) &&
        Objects.equals(this.valor, dadesOperacionsDadesBDTO.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, grup, id, idDefinicioGrup, itemsList, ordre, tipus, titol, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadesOperacionsDadesBDTO {\n");
    
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    grup: ").append(toIndentedString(grup)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idDefinicioGrup: ").append(toIndentedString(idDefinicioGrup)).append("\n");
    sb.append("    itemsList: ").append(toIndentedString(itemsList)).append("\n");
    sb.append("    ordre: ").append(toIndentedString(ordre)).append("\n");
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    titol: ").append(toIndentedString(titol)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

