/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 1.13.2
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * PageDataOfPersonesSollicitudRDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-14T14:00:28.664+02:00")
public class PageDataOfPersonesSollicitudRDTO {
  @JsonProperty("data")
  private List<PersonesSollicitudRDTO> data = null;

  @JsonProperty("page")
  private PaginationAttributes page = null;

  @JsonProperty("sortInfo")
  private SortInfo sortInfo = null;

  public PageDataOfPersonesSollicitudRDTO data(List<PersonesSollicitudRDTO> data) {
    this.data = data;
    return this;
  }

  public PageDataOfPersonesSollicitudRDTO addDataItem(PersonesSollicitudRDTO dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<PersonesSollicitudRDTO>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public List<PersonesSollicitudRDTO> getData() {
    return data;
  }

  public void setData(List<PersonesSollicitudRDTO> data) {
    this.data = data;
  }

  public PageDataOfPersonesSollicitudRDTO page(PaginationAttributes page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(value = "")
  public PaginationAttributes getPage() {
    return page;
  }

  public void setPage(PaginationAttributes page) {
    this.page = page;
  }

  public PageDataOfPersonesSollicitudRDTO sortInfo(SortInfo sortInfo) {
    this.sortInfo = sortInfo;
    return this;
  }

   /**
   * Get sortInfo
   * @return sortInfo
  **/
  @ApiModelProperty(value = "")
  public SortInfo getSortInfo() {
    return sortInfo;
  }

  public void setSortInfo(SortInfo sortInfo) {
    this.sortInfo = sortInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageDataOfPersonesSollicitudRDTO pageDataOfPersonesSollicitudRDTO = (PageDataOfPersonesSollicitudRDTO) o;
    return Objects.equals(this.data, pageDataOfPersonesSollicitudRDTO.data) &&
        Objects.equals(this.page, pageDataOfPersonesSollicitudRDTO.page) &&
        Objects.equals(this.sortInfo, pageDataOfPersonesSollicitudRDTO.sortInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, page, sortInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageDataOfPersonesSollicitudRDTO {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    sortInfo: ").append(toIndentedString(sortInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

