/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 2.10.3
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * RespostaUnitatsExpedient
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-11-08T15:53:07.446+01:00")
public class RespostaUnitatsExpedient {
  @JsonProperty("idUnitatGestora")
  private BigDecimal idUnitatGestora = null;

  @JsonProperty("idUnitatGestoraConvidadaList")
  private List<BigDecimal> idUnitatGestoraConvidadaList = null;

  @JsonProperty("idUnitatGestoraResponsable")
  private BigDecimal idUnitatGestoraResponsable = null;

  public RespostaUnitatsExpedient idUnitatGestora(BigDecimal idUnitatGestora) {
    this.idUnitatGestora = idUnitatGestora;
    return this;
  }

   /**
   * Unitat gestora de l&#39;expedient
   * @return idUnitatGestora
  **/
  @ApiModelProperty(value = "Unitat gestora de l'expedient")
  public BigDecimal getIdUnitatGestora() {
    return idUnitatGestora;
  }

  public void setIdUnitatGestora(BigDecimal idUnitatGestora) {
    this.idUnitatGestora = idUnitatGestora;
  }

  public RespostaUnitatsExpedient idUnitatGestoraConvidadaList(List<BigDecimal> idUnitatGestoraConvidadaList) {
    this.idUnitatGestoraConvidadaList = idUnitatGestoraConvidadaList;
    return this;
  }

  public RespostaUnitatsExpedient addIdUnitatGestoraConvidadaListItem(BigDecimal idUnitatGestoraConvidadaListItem) {
    if (this.idUnitatGestoraConvidadaList == null) {
      this.idUnitatGestoraConvidadaList = new ArrayList<BigDecimal>();
    }
    this.idUnitatGestoraConvidadaList.add(idUnitatGestoraConvidadaListItem);
    return this;
  }

   /**
   * Llista unitats gestoras convidadas de l&#39;expedient
   * @return idUnitatGestoraConvidadaList
  **/
  @ApiModelProperty(value = "Llista unitats gestoras convidadas de l'expedient")
  public List<BigDecimal> getIdUnitatGestoraConvidadaList() {
    return idUnitatGestoraConvidadaList;
  }

  public void setIdUnitatGestoraConvidadaList(List<BigDecimal> idUnitatGestoraConvidadaList) {
    this.idUnitatGestoraConvidadaList = idUnitatGestoraConvidadaList;
  }

  public RespostaUnitatsExpedient idUnitatGestoraResponsable(BigDecimal idUnitatGestoraResponsable) {
    this.idUnitatGestoraResponsable = idUnitatGestoraResponsable;
    return this;
  }

   /**
   * Unitat gestora responsable de l&#39;procediment
   * @return idUnitatGestoraResponsable
  **/
  @ApiModelProperty(value = "Unitat gestora responsable de l'procediment")
  public BigDecimal getIdUnitatGestoraResponsable() {
    return idUnitatGestoraResponsable;
  }

  public void setIdUnitatGestoraResponsable(BigDecimal idUnitatGestoraResponsable) {
    this.idUnitatGestoraResponsable = idUnitatGestoraResponsable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaUnitatsExpedient respostaUnitatsExpedient = (RespostaUnitatsExpedient) o;
    return Objects.equals(this.idUnitatGestora, respostaUnitatsExpedient.idUnitatGestora) &&
        Objects.equals(this.idUnitatGestoraConvidadaList, respostaUnitatsExpedient.idUnitatGestoraConvidadaList) &&
        Objects.equals(this.idUnitatGestoraResponsable, respostaUnitatsExpedient.idUnitatGestoraResponsable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idUnitatGestora, idUnitatGestoraConvidadaList, idUnitatGestoraResponsable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaUnitatsExpedient {\n");
    
    sb.append("    idUnitatGestora: ").append(toIndentedString(idUnitatGestora)).append("\n");
    sb.append("    idUnitatGestoraConvidadaList: ").append(toIndentedString(idUnitatGestoraConvidadaList)).append("\n");
    sb.append("    idUnitatGestoraResponsable: ").append(toIndentedString(idUnitatGestoraResponsable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

