/*
 * API gpadocumentacio
 * API gpadocumentacio
 *
 * OpenAPI spec version: 1.11.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.gpadocumentacio;

import es.bcn.gpa.gpaserveis.rest.client.api.model.gpadocumentacio.CategoriaNtiRDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoriaNtiApi
 */
@Ignore
public class CategoriaNtiApiTest {

    private final CategoriaNtiApi api = new CategoriaNtiApi();

    
    /**
     * Returns all the categoriaNti
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoriaNtiUsingGETTest() {
        List<CategoriaNtiRDTO> response = api.getCategoriaNtiUsingGET();

        // TODO: test validations
    }
    
}
