/*
 * API gpadocumentacio
 * API gpadocumentacio
 *
 * OpenAPI spec version: 1.13.1
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.bcn.gpa.gpaserveis.rest.client.api.gpadocumentacio;

import static java.math.BigDecimal.ONE;
import static org.apache.commons.lang.math.NumberUtils.INTEGER_ONE;
import static org.junit.Assert.assertTrue;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.when;

import java.math.BigDecimal;
import java.util.List;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.mockito.InjectMocks;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.util.MultiValueMap;

/**
 * API tests for DownloadApi
 */
@SuppressWarnings("unchecked")
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class DownloadApiTest extends ParentTest {

	@InjectMocks
	private DownloadApi api = new DownloadApi();

	/**
	 * Downloads the document
	 *
	 * 
	 *
	 * @throws ApiException
	 *             if the Api call fails
	 */
	@Test
	public void descarregarDocumentExpedientTest() {
		when(apiClient.invokeAPI(eq("/documentacio/descarregarDocument/1/1"), eq(HttpMethod.GET), any(MultiValueMap.class),
		        any(Object.class), any(HttpHeaders.class), any(MultiValueMap.class), any(List.class), any(MediaType.class),
		        any(String[].class), any(ParameterizedTypeReference.class))).thenReturn("prova".getBytes());

		BigDecimal idDoc = ONE;
		BigDecimal idExpedient = ONE;
		byte[] response = api.descarregarDocumentExpedient(idDoc, idExpedient);

		assertTrue(response != null);
	}

	/**
	 * Downloads the document by pos
	 *
	 * 
	 *
	 * @throws ApiException
	 *             if the Api call fails
	 */
	@Test
	public void descarregarDocumentExpedientByPosTest() {
		when(apiClient.invokeAPI(eq("/documentacio/descarregarDocumentByPos/1/1/1"), eq(HttpMethod.GET), any(MultiValueMap.class),
		        any(Object.class), any(HttpHeaders.class), any(MultiValueMap.class), any(List.class), any(MediaType.class),
		        any(String[].class), any(ParameterizedTypeReference.class))).thenReturn("prova".getBytes());

		BigDecimal idDoc = ONE;
		BigDecimal idExpedient = ONE;
		Integer pos = INTEGER_ONE;
		byte[] response = api.descarregarDocumentExpedientByPos(idDoc, idExpedient, pos);

		assertTrue(response != null);
	}
}
