/*
 * API gpadocumentacio
 * API gpadocumentacio
 *
 * OpenAPI spec version: 1.11.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.gpadocumentacio;

import es.bcn.gpa.gpaserveis.rest.client.api.model.gpadocumentacio.ProcedimentSerieDocRDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpadocumentacio.RespostaSincronitzarCheckRDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpadocumentacio.RespostaSincronitzarRDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpadocumentacio.SerieDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SeriesCatalegApi
 */
@Ignore
public class SeriesCatalegApiTest {

    private final SeriesCatalegApi api = new SeriesCatalegApi();

    
    /**
     * Sincronitzar la configuració de la documentació del procediment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkSerieDocumentalUsingGETTest() {
        String serieDocumental = null;
        RespostaSincronitzarCheckRDTO response = api.checkSerieDocumentalUsingGET(serieDocumental);

        // TODO: test validations
    }
    
    /**
     * Returns the series
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSeriesUsingGETTest() {
        List<SerieDTO> response = api.getSeriesUsingGET();

        // TODO: test validations
    }
    
    /**
     * Sincronitzar la configuració de la documentació del procediment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sincronitzarSeriesToProcUsingPOSTTest() {
        ProcedimentSerieDocRDTO procedimentSerieDocRDTO = null;
        RespostaSincronitzarRDTO response = api.sincronitzarSeriesToProcUsingPOST(procedimentSerieDocRDTO);

        // TODO: test validations
    }
    
    /**
     * Sincronitzar la configuració de la documentació del procediment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sincronitzarUsingPOSTTest() {
        ProcedimentSerieDocRDTO procedimentSerieDocRDTO = null;
        RespostaSincronitzarRDTO response = api.sincronitzarUsingPOST(procedimentSerieDocRDTO);

        // TODO: test validations
    }
    
}
