---
swagger: "2.0"
info:
  description: "API gpatramits"
  version: "1.16.2"
  title: "API gpatramits"
  contact:
    name: "Sergio Corras"
    email: "sergio.corras@iecisa.com"
  license:
    name: "Llicència IMI"
basePath: "/services/gpatramits/rest"
tags:
- name: "tramits-ovt-rest-controller"
  description: "Tramits Ovt Rest Controller"
- name: "tramits-rest-controller"
  description: "Tramits Rest Controller"
paths:
  /tramits/accionsEstatsForEstatActualAndAccio/{idEstatActual}/{idAccio}:
    get:
      tags:
      - "AccionsEstats"
      summary: "Returns the transition for the current expedient's status and action\
        \ execution"
      operationId: "cercaTransicioCanviEstat"
      produces:
      - "*/*"
      parameters:
      - name: "idAccio"
        in: "path"
        description: "idAccio"
        required: true
        type: "number"
      - name: "idEstatActual"
        in: "path"
        description: "idEstatActual"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AccionsEstatsRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /tramits/accionsPermesesForEstatActual/{estatId}:
    get:
      tags:
      - "AccionsEstats"
      summary: "Returns the accions allowed for the current expedient's status"
      operationId: "cercaAccionsPossibles"
      produces:
      - "*/*"
      parameters:
      - name: "estatId"
        in: "path"
        description: "estatId"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AccionsEstatsRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /tramits/searchAssociated/procediment/{idProcediment}:
    get:
      tags:
      - "Tramits"
      summary: "Returns all the tramits that meet the search criteria and are associated\
        \ with a procediment"
      operationId: "cercaTramitsProcediment"
      produces:
      - "*/*"
      parameters:
      - name: "absoluteRowNumberOfFirstRowInCurrentPage"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "absoluteRowNumberOfLastRowInCurrentPage"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "bloqueig"
        in: "query"
        required: false
        type: "number"
      - name: "bloquejos.id"
        in: "query"
        required: false
        type: "number"
      - name: "bloquejos.momentBloqueig"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "bloquejos.tipus"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.tramitBloquejatPerAltreUsuari"
        in: "query"
        required: false
        type: "boolean"
      - name: "bloquejos.tramitEditable"
        in: "query"
        required: false
        type: "boolean"
      - name: "bloquejos.usuari"
        in: "query"
        required: false
        type: "number"
      - name: "bloquejos.usuariBloquejo.carrec"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.cognom1"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.cognom2"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.documentIdentitat"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.email"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.grp"
        in: "query"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "bloquejos.usuariBloquejo.id"
        in: "query"
        required: false
        type: "number"
      - name: "bloquejos.usuariBloquejo.matricula"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.nom"
        in: "query"
        required: false
        type: "string"
      - name: "bloquejos.usuariBloquejo.user"
        in: "query"
        required: false
        type: "string"
      - name: "currentPageHasNextPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageHasPreviousPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageIsFirstPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageIsLastPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageNumber"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "darreraModificacio"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "dataGestioElectronica"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "descripcio"
        in: "query"
        required: false
        type: "string"
      - name: "descripcioEstatTramit"
        in: "query"
        required: false
        type: "string"
      - name: "dir"
        in: "query"
        required: false
        type: "string"
      - name: "esTramitIniciacio"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "estatTramit"
        in: "query"
        required: false
        type: "number"
      - name: "estatsTramit.estat"
        in: "query"
        required: false
        type: "number"
      - name: "estatsTramit.estatTramitAnt"
        in: "query"
        required: false
        type: "number"
      - name: "estatsTramit.estatsTramits.descripcio"
        in: "query"
        required: false
        type: "string"
      - name: "estatsTramit.estatsTramits.id"
        in: "query"
        required: false
        type: "number"
      - name: "estatsTramit.historic"
        in: "query"
        required: false
        type: "number"
      - name: "estatsTramit.id"
        in: "query"
        required: false
        type: "number"
      - name: "estatsTramit.tramit"
        in: "query"
        required: false
        type: "number"
      - name: "exclusiuIntern"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "gestioElectronica"
        in: "query"
        required: false
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "number"
      - name: "idProcediment"
        in: "path"
        description: "idProcediment"
        required: true
        type: "number"
      - name: "informacioTramitador"
        in: "query"
        required: false
        type: "string"
      - name: "nextPageNumber"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "nom"
        in: "query"
        required: false
        type: "string"
      - name: "normaAltresAplicacio"
        in: "query"
        required: false
        type: "string"
      - name: "normaReferenciaPrincipal"
        in: "query"
        required: false
        type: "string"
      - name: "pageSize"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "previousPageNumber"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "rolUsuari"
        in: "query"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        required: false
        type: "string"
      - name: "totalElements"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "totalPages"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "ultimaModificacio"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/PageDataOfTramitsRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /tramits/{id}:
    get:
      tags:
      - "Tramits"
      summary: "Returns the requested tramits"
      operationId: "consultarDadesTramit"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/TramitsRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /tramitsOvt/{id}:
    get:
      tags:
      - "TramitsOVT"
      summary: "Returns the requested tràmit OVT"
      operationId: "consultarDadesTramitOvt"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/TramitsOvtRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
definitions:
  AccionsEstatsRDTO:
    type: "object"
    properties:
      accio:
        type: "number"
      descTransicio:
        type: "string"
      esEstatFinal:
        type: "integer"
        format: "int32"
      esEstatInicial:
        type: "integer"
        format: "int32"
      estat:
        type: "number"
      estatCiutada:
        type: "string"
      estatCiutadaCastella:
        type: "string"
      estatCiutadaCatala:
        type: "string"
      estatTramitador:
        type: "string"
      estatTramitadorCastella:
        type: "string"
      estatTramitadorCatala:
        type: "string"
      id:
        type: "number"
      nomAccio:
        type: "string"
    title: "AccionsEstatsRDTO"
  Bloquejos:
    type: "object"
    properties:
      id:
        type: "number"
      momentBloqueig:
        type: "string"
        format: "date-time"
      tipus:
        type: "string"
      tramitBloquejatPerAltreUsuari:
        type: "boolean"
      tramitEditable:
        type: "boolean"
      usuari:
        type: "number"
      usuariBloquejo:
        $ref: "#/definitions/Usuaris"
    title: "Bloquejos"
  EstatsTramit:
    type: "object"
    properties:
      estat:
        type: "number"
      estatTramitAnt:
        type: "number"
      estatsTramitAnt:
        $ref: "#/definitions/EstatsTramit"
      estatsTramits:
        $ref: "#/definitions/EstatsTramits"
      historic:
        type: "number"
      id:
        type: "number"
      tramit:
        type: "number"
    title: "EstatsTramit"
  EstatsTramits:
    type: "object"
    properties:
      descripcio:
        type: "string"
      id:
        type: "number"
    title: "EstatsTramits"
  PageDataOfTramitsRDTO:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/TramitsRDTO"
      page:
        $ref: "#/definitions/PaginationAttributes"
      sortInfo:
        $ref: "#/definitions/SortInfo"
    title: "PageDataOfTramitsRDTO"
  PaginationAttributes:
    type: "object"
    properties:
      absoluteRowNumberOfFirstRowInCurrentPage:
        type: "integer"
        format: "int32"
      absoluteRowNumberOfLastRowInCurrentPage:
        type: "integer"
        format: "int32"
      currentPageHasNextPage:
        type: "boolean"
      currentPageHasPreviousPage:
        type: "boolean"
      currentPageIsFirstPage:
        type: "boolean"
      currentPageIsLastPage:
        type: "boolean"
      currentPageNumber:
        type: "integer"
        format: "int32"
      nextPageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      previousPageNumber:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
    title: "PaginationAttributes"
  SortInfo:
    type: "object"
    properties:
      dir:
        type: "string"
      sort:
        type: "string"
    title: "SortInfo"
  TramitsOvtRDTO:
    type: "object"
    properties:
      descripcio:
        type: "string"
      id:
        type: "number"
    title: "TramitsOvtRDTO"
  TramitsRDTO:
    type: "object"
    properties:
      bloqueig:
        type: "number"
      bloquejos:
        $ref: "#/definitions/Bloquejos"
      darreraModificacio:
        type: "string"
        format: "date-time"
      dataGestioElectronica:
        type: "string"
        format: "date-time"
      descripcio:
        type: "string"
      descripcioEstatTramit:
        type: "string"
      esTramitIniciacio:
        type: "integer"
        format: "int32"
      estatTramit:
        type: "number"
      estatsTramit:
        $ref: "#/definitions/EstatsTramit"
      exclusiuIntern:
        type: "integer"
        format: "int32"
      gestioElectronica:
        type: "string"
      id:
        type: "number"
      informacioTramitador:
        type: "string"
      nom:
        type: "string"
      normaAltresAplicacio:
        type: "string"
      normaReferenciaPrincipal:
        type: "string"
      rolUsuari:
        type: "string"
      ultimaModificacio:
        type: "number"
    title: "TramitsRDTO"
  Usuaris:
    type: "object"
    properties:
      carrec:
        type: "string"
      cognom1:
        type: "string"
      cognom2:
        type: "string"
      documentIdentitat:
        type: "string"
      email:
        type: "string"
      grp:
        type: "array"
        items:
          type: "string"
      id:
        type: "number"
      matricula:
        type: "string"
      nom:
        type: "string"
      user:
        type: "string"
    title: "Usuaris"
