---
swagger: "2.0"
info:
  description: "API gpaunitats"
  version: "1.16.2"
  title: "API gpaunitats"
  contact:
    name: "Sergio Corras"
    email: "sergio.corras@iecisa.com"
  license:
    name: "Llicència IMI"
basePath: "/services/gpaunitats/rest"
tags:
- name: "contexte-seguretat-rest-controller"
  description: "Contexte Seguretat Rest Controller"
- name: "unitats-rest-controller"
  description: "Unitats Rest Controller"
paths:
  /autenticacioUsuaris/autenticat:
    get:
      tags:
      - "Usuaris"
      summary: "Returns the requested usuari"
      operationId: "obtenirUsuariAutenticat"
      produces:
      - "*/*"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UsuarisRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /unitats/obtenirIdsUnitatsPerNomList/{nomList}:
    get:
      tags:
      - "Unitats Gestores"
      summary: "Returns the requested unitat"
      operationId: "consultarDadesUnitatGestoraPerNomList"
      produces:
      - "*/*"
      parameters:
      - name: "nomList"
        in: "path"
        description: "nomList"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              type: "number"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /unitats/perNom/{nom}:
    get:
      tags:
      - "Unitats Gestores"
      summary: "Returns the requested unitat"
      operationId: "consultarDadesUnitatGestoraPerNom"
      produces:
      - "*/*"
      parameters:
      - name: "nom"
        in: "path"
        description: "nom"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UnitatsGestoresRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /unitats/search:
    get:
      tags:
      - "Unitats Gestores"
      summary: "Returns all the unitats that meet the search criteria"
      operationId: "cercaUnitatsGestores"
      produces:
      - "*/*"
      parameters:
      - name: "absoluteRowNumberOfFirstRowInCurrentPage"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "absoluteRowNumberOfLastRowInCurrentPage"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "currentPageHasNextPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageHasPreviousPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageIsFirstPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageIsLastPage"
        in: "query"
        required: false
        type: "boolean"
      - name: "currentPageNumber"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "darreraSincronitzacio"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "dataCreacio"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "dataModificacio"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "descUnitatOrganigrama"
        in: "query"
        required: false
        type: "string"
      - name: "descripcio"
        in: "query"
        required: false
        type: "string"
      - name: "dir"
        in: "query"
        required: false
        type: "string"
      - name: "id"
        in: "query"
        required: false
        type: "number"
      - name: "idGrup"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "nextPageNumber"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "nom"
        in: "query"
        required: false
        type: "string"
      - name: "nomDescripcio"
        in: "query"
        required: false
        type: "string"
      - name: "pageSize"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "previousPageNumber"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "sort"
        in: "query"
        required: false
        type: "string"
      - name: "totalElements"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "totalPages"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      - name: "unitatOrganigrama"
        in: "query"
        required: false
        type: "number"
      - name: "unitatOrganigramaList"
        in: "query"
        required: false
        type: "array"
        items:
          type: "number"
        collectionFormat: "multi"
      - name: "vigent"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/PageDataOfUnitatsGestoresRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /unitats/{id}:
    get:
      tags:
      - "Unitats Gestores"
      summary: "Returns the requested unitat"
      operationId: "consultarDadesUnitatGestora"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UnitatsGestoresRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
  /unitats/{id}/unitatOrganigrama:
    get:
      tags:
      - "Unitats Gestores"
      summary: "Returns the requested unitat"
      operationId: "consultarUnitatOrganigrama"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UnitatsOrganigramaRDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
      deprecated: false
      x-imi-roles:
        consulta: "Perfil usuari consulta"
definitions:
  PageDataOfUnitatsGestoresRDTO:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/UnitatsGestoresRDTO"
      page:
        $ref: "#/definitions/PaginationAttributes"
      sortInfo:
        $ref: "#/definitions/SortInfo"
    title: "PageDataOfUnitatsGestoresRDTO"
  PaginationAttributes:
    type: "object"
    properties:
      absoluteRowNumberOfFirstRowInCurrentPage:
        type: "integer"
        format: "int32"
      absoluteRowNumberOfLastRowInCurrentPage:
        type: "integer"
        format: "int32"
      currentPageHasNextPage:
        type: "boolean"
      currentPageHasPreviousPage:
        type: "boolean"
      currentPageIsFirstPage:
        type: "boolean"
      currentPageIsLastPage:
        type: "boolean"
      currentPageNumber:
        type: "integer"
        format: "int32"
      nextPageNumber:
        type: "integer"
        format: "int32"
      pageSize:
        type: "integer"
        format: "int32"
      previousPageNumber:
        type: "integer"
        format: "int32"
      totalElements:
        type: "integer"
        format: "int64"
      totalPages:
        type: "integer"
        format: "int32"
    title: "PaginationAttributes"
  SortInfo:
    type: "object"
    properties:
      dir:
        type: "string"
      sort:
        type: "string"
    title: "SortInfo"
  UnitatsGestoresRDTO:
    type: "object"
    properties:
      darreraSincronitzacio:
        type: "string"
        format: "date-time"
      dataCreacio:
        type: "string"
        format: "date-time"
      dataModificacio:
        type: "string"
        format: "date-time"
      descUnitatOrganigrama:
        type: "string"
      descripcio:
        type: "string"
      id:
        type: "number"
      idGrup:
        type: "integer"
        format: "int64"
      nom:
        type: "string"
      nomDescripcio:
        type: "string"
      unitatOrganigrama:
        type: "number"
      unitatOrganigramaList:
        type: "array"
        items:
          type: "number"
      vigent:
        type: "integer"
        format: "int32"
    title: "UnitatsGestoresRDTO"
  UnitatsOrganigramaRDTO:
    type: "object"
    properties:
      codi:
        type: "string"
      id:
        type: "number"
      nom:
        type: "string"
    title: "UnitatsOrganigramaRDTO"
  UsuarisRDTO:
    type: "object"
    properties:
      carrec:
        type: "string"
      cognom1:
        type: "string"
      cognom2:
        type: "string"
      documentIdentitat:
        type: "string"
      email:
        type: "string"
      grp:
        type: "array"
        items:
          type: "string"
      id:
        type: "number"
      matricula:
        type: "string"
      nom:
        type: "string"
    title: "UsuarisRDTO"
