//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.26 at 02:43:07 AM CET 
//


package es.bcn.gpa.gpaserveis.web.rest.dto.serveis.mcisignatures.notificacions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for signaturaResultatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="signaturaResultatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idSignatura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refDocumentSignat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="estatSignatura" type="{}estatSignaturaType"/>
 *         &lt;element name="metadades" type="{}metadadesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signaturaResultatType", propOrder = {
    "idSignatura",
    "refDocumentSignat",
    "estatSignatura",
    "metadades"
})
public class SignaturaResultatType {

    @XmlElement(required = true)
    protected String idSignatura;
    @XmlElement(required = true)
    protected String refDocumentSignat;
    @XmlElement(required = true)
    protected EstatSignaturaType estatSignatura;
    @XmlElement(required = true)
    protected MetadadesType metadades;

    /**
     * Gets the value of the idSignatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSignatura() {
        return idSignatura;
    }

    /**
     * Sets the value of the idSignatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSignatura(String value) {
        this.idSignatura = value;
    }

    /**
     * Gets the value of the refDocumentSignat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDocumentSignat() {
        return refDocumentSignat;
    }

    /**
     * Sets the value of the refDocumentSignat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDocumentSignat(String value) {
        this.refDocumentSignat = value;
    }

    /**
     * Gets the value of the estatSignatura property.
     * 
     * @return
     *     possible object is
     *     {@link EstatSignaturaType }
     *     
     */
    public EstatSignaturaType getEstatSignatura() {
        return estatSignatura;
    }

    /**
     * Sets the value of the estatSignatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstatSignaturaType }
     *     
     */
    public void setEstatSignatura(EstatSignaturaType value) {
        this.estatSignatura = value;
    }

    /**
     * Gets the value of the metadades property.
     * 
     * @return
     *     possible object is
     *     {@link MetadadesType }
     *     
     */
    public MetadadesType getMetadades() {
        return metadades;
    }

    /**
     * Sets the value of the metadades property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadadesType }
     *     
     */
    public void setMetadades(MetadadesType value) {
        this.metadades = value;
    }

}
