/*
 * API gpatramits
 * API gpatramits
 *
 * OpenAPI spec version: 1.8.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpatramits;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * EstatsRDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-02T03:58:39.261+02:00")
public class EstatsRDTO {
  @JsonProperty("estatCiutada")
  private String estatCiutada = null;

  @JsonProperty("estatCiutadaCastella")
  private String estatCiutadaCastella = null;

  @JsonProperty("estatCiutadaCatala")
  private String estatCiutadaCatala = null;

  @JsonProperty("estatTramitador")
  private String estatTramitador = null;

  @JsonProperty("estatTramitadorCastella")
  private String estatTramitadorCastella = null;

  @JsonProperty("estatTramitadorCatala")
  private String estatTramitadorCatala = null;

  @JsonProperty("id")
  private BigDecimal id = null;

  public EstatsRDTO estatCiutada(String estatCiutada) {
    this.estatCiutada = estatCiutada;
    return this;
  }

   /**
   * Get estatCiutada
   * @return estatCiutada
  **/
  @ApiModelProperty(value = "")
  public String getEstatCiutada() {
    return estatCiutada;
  }

  public void setEstatCiutada(String estatCiutada) {
    this.estatCiutada = estatCiutada;
  }

  public EstatsRDTO estatCiutadaCastella(String estatCiutadaCastella) {
    this.estatCiutadaCastella = estatCiutadaCastella;
    return this;
  }

   /**
   * Get estatCiutadaCastella
   * @return estatCiutadaCastella
  **/
  @ApiModelProperty(value = "")
  public String getEstatCiutadaCastella() {
    return estatCiutadaCastella;
  }

  public void setEstatCiutadaCastella(String estatCiutadaCastella) {
    this.estatCiutadaCastella = estatCiutadaCastella;
  }

  public EstatsRDTO estatCiutadaCatala(String estatCiutadaCatala) {
    this.estatCiutadaCatala = estatCiutadaCatala;
    return this;
  }

   /**
   * Get estatCiutadaCatala
   * @return estatCiutadaCatala
  **/
  @ApiModelProperty(value = "")
  public String getEstatCiutadaCatala() {
    return estatCiutadaCatala;
  }

  public void setEstatCiutadaCatala(String estatCiutadaCatala) {
    this.estatCiutadaCatala = estatCiutadaCatala;
  }

  public EstatsRDTO estatTramitador(String estatTramitador) {
    this.estatTramitador = estatTramitador;
    return this;
  }

   /**
   * Get estatTramitador
   * @return estatTramitador
  **/
  @ApiModelProperty(value = "")
  public String getEstatTramitador() {
    return estatTramitador;
  }

  public void setEstatTramitador(String estatTramitador) {
    this.estatTramitador = estatTramitador;
  }

  public EstatsRDTO estatTramitadorCastella(String estatTramitadorCastella) {
    this.estatTramitadorCastella = estatTramitadorCastella;
    return this;
  }

   /**
   * Get estatTramitadorCastella
   * @return estatTramitadorCastella
  **/
  @ApiModelProperty(value = "")
  public String getEstatTramitadorCastella() {
    return estatTramitadorCastella;
  }

  public void setEstatTramitadorCastella(String estatTramitadorCastella) {
    this.estatTramitadorCastella = estatTramitadorCastella;
  }

  public EstatsRDTO estatTramitadorCatala(String estatTramitadorCatala) {
    this.estatTramitadorCatala = estatTramitadorCatala;
    return this;
  }

   /**
   * Get estatTramitadorCatala
   * @return estatTramitadorCatala
  **/
  @ApiModelProperty(value = "")
  public String getEstatTramitadorCatala() {
    return estatTramitadorCatala;
  }

  public void setEstatTramitadorCatala(String estatTramitadorCatala) {
    this.estatTramitadorCatala = estatTramitadorCatala;
  }

  public EstatsRDTO id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstatsRDTO estatsRDTO = (EstatsRDTO) o;
    return Objects.equals(this.estatCiutada, estatsRDTO.estatCiutada) &&
        Objects.equals(this.estatCiutadaCastella, estatsRDTO.estatCiutadaCastella) &&
        Objects.equals(this.estatCiutadaCatala, estatsRDTO.estatCiutadaCatala) &&
        Objects.equals(this.estatTramitador, estatsRDTO.estatTramitador) &&
        Objects.equals(this.estatTramitadorCastella, estatsRDTO.estatTramitadorCastella) &&
        Objects.equals(this.estatTramitadorCatala, estatsRDTO.estatTramitadorCatala) &&
        Objects.equals(this.id, estatsRDTO.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(estatCiutada, estatCiutadaCastella, estatCiutadaCatala, estatTramitador, estatTramitadorCastella, estatTramitadorCatala, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstatsRDTO {\n");
    
    sb.append("    estatCiutada: ").append(toIndentedString(estatCiutada)).append("\n");
    sb.append("    estatCiutadaCastella: ").append(toIndentedString(estatCiutadaCastella)).append("\n");
    sb.append("    estatCiutadaCatala: ").append(toIndentedString(estatCiutadaCatala)).append("\n");
    sb.append("    estatTramitador: ").append(toIndentedString(estatTramitador)).append("\n");
    sb.append("    estatTramitadorCastella: ").append(toIndentedString(estatTramitadorCastella)).append("\n");
    sb.append("    estatTramitadorCatala: ").append(toIndentedString(estatTramitadorCatala)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

