 -- ------------------------------------------------------------------------------------
 --
 -- Descripció: Script de creació: GPASERVEIS_T.sql.
 -- Usuari Oracle: GPAPSERVEIS_U
 -- Proveïdor: IECISA
 -- Data: 03-12-2018
 --
 -- ------------------------------------------------------------------------------------
 
 
/* Create Tables */
CREATE TABLE  "AUDIT_SERVEIS_PORTAL"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_TRAMITADORS"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_NOTIFICACIONS"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_PORTASIGNATURES"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_MDS"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);


/* Create Sequences */
CREATE SEQUENCE "SERVEIS_PORTAL_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_TRAM_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_NOTIF_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_PORTASIG_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_MDS_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
