/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 1.15.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.gpaexpedients;

import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.AvisosRDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.CrearAvisDocEntradaPendentRevisio;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CrearAvisDocumentaciEntradaPendentRevisiApi
 */
@Ignore
public class CrearAvisDocumentaciEntradaPendentRevisiApiTest {

    private final CrearAvisDocumentaciEntradaPendentRevisiApi api = new CrearAvisDocumentaciEntradaPendentRevisiApi();

    
    /**
     * Crear Avis Documentació Entrada Pendent Revisió
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crearAvisDocEntradaPendentRevisioUsingPOSTTest() {
        CrearAvisDocEntradaPendentRevisio crearAvisDocEntradaPendentRevisioRDTO = null;
        api.crearAvisDocEntradaPendentRevisioUsingPOST(crearAvisDocEntradaPendentRevisioRDTO);

        // TODO: test validations
    }
    
    /**
     * Crear Avis
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crearAvisUsingPOSTTest() {
        AvisosRDTO avisosRDTO = null;
        api.crearAvisUsingPOST(avisosRDTO);

        // TODO: test validations
    }
    
}
