/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 1.11.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.gpaexpedients;

import es.bcn.gpa.gpaserveis.rest.client.invoker.gpaexpedients.ApiException;
import java.math.BigDecimal;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.DadesEspecifiquesRDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DadesEspecifiquesApi
 */
@Ignore
public class DadesEspecifiquesApiTest {

    private final DadesEspecifiquesApi api = new DadesEspecifiquesApi();

    
    /**
     * Returns the requested dades especifiques
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultarDadesEspecifiquesExpedientTest() throws ApiException {
        BigDecimal idExpedient = null;
        List<DadesEspecifiquesRDTO> response = api.consultarDadesEspecifiquesExpedient(idExpedient);

        // TODO: test validations
    }
    
    /**
     * Insert  or updates the provided dades especifiques
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveOrUpdateUsingPOSTTest() throws ApiException {
        List<DadesEspecifiquesRDTO> dadesEspecifiquesRDTOList = null;
        api.saveOrUpdateUsingPOST(dadesEspecifiquesRDTOList);

        // TODO: test validations
    }
    
}
