/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 1.11.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.gpaexpedients;

import es.bcn.gpa.gpaserveis.rest.client.invoker.gpaexpedients.ApiException;
import java.math.BigDecimal;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.CanviEstatRDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.DropdownItemRDTO;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.EstatsRDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EstatsApi
 */
@Ignore
public class EstatsApiTest {

    private final EstatsApi api = new EstatsApi();

    
    /**
     * Returns the historic of states through which the expedient has passed
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cercaHistoricsEstatsTest() throws ApiException {
        BigDecimal idExpedient = null;
        List<EstatsRDTO> response = api.cercaHistoricsEstats(idExpedient);

        // TODO: test validations
    }
    
    /**
     * Returns the requested estats
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEstatsByIdExpedientUsingGETTest() throws ApiException {
        BigDecimal idExpedient = null;
        CanviEstatRDTO response = api.getEstatsByIdExpedientUsingGET(idExpedient);

        // TODO: test validations
    }
    
    /**
     * Returns the requested estats
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOperacionsByAccioEstatIdextUsingGETTest() throws ApiException {
        BigDecimal accioEstatIdext = null;
        List<DropdownItemRDTO> response = api.getOperacionsByAccioEstatIdextUsingGET(accioEstatIdext);

        // TODO: test validations
    }
    
}
