/*
 * API gpaexpedients
 * API gpaexpedients
 *
 * OpenAPI spec version: 1.15.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.gpaexpedients;

import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaexpedients.TipusPersonaRDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TipusPersonaApi
 */
@Ignore
public class TipusPersonaApiTest {

    private final TipusPersonaApi api = new TipusPersonaApi();

    
    /**
     * Returns all the TipusPersonas
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTipusPersonaUsingGETTest() {
        List<TipusPersonaRDTO> response = api.getTipusPersonaUsingGET();

        // TODO: test validations
    }
    
}
