/*
 * API gpadocumentacio
 * API gpadocumentacio
 *
 * OpenAPI spec version: 2.10.0
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpadocumentacio;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * ExpedientGestorDocumentalRDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-11-04T14:21:11.408+01:00")
public class ExpedientGestorDocumentalRDTO {
  @JsonProperty("codiExpRelacionat")
  private String codiExpRelacionat = null;

  @JsonProperty("codiExpedient")
  private String codiExpedient = null;

  @JsonProperty("codiLlargExpedient")
  private String codiLlargExpedient = null;

  @JsonProperty("codiUnitatOrganigrama")
  private String codiUnitatOrganigrama = null;

  @JsonProperty("cognom1Sollicitant")
  private String cognom1Sollicitant = null;

  @JsonProperty("cognom2Sollicitant")
  private String cognom2Sollicitant = null;

  @JsonProperty("dataRegistre")
  private String dataRegistre = null;

  @JsonProperty("descEstadoExp")
  private String descEstadoExp = null;

  @JsonProperty("destinatariRegistre")
  private String destinatariRegistre = null;

  @JsonProperty("documentErroni")
  private String documentErroni = null;

  @JsonProperty("documentIdentitatSollicitant")
  private String documentIdentitatSollicitant = null;

  @JsonProperty("documentacioIdext")
  private BigDecimal documentacioIdext = null;

  @JsonProperty("fechaFinExp")
  private String fechaFinExp = null;

  @JsonProperty("fechaIniExp")
  private String fechaIniExp = null;

  @JsonProperty("idEstat")
  private BigDecimal idEstat = null;

  @JsonProperty("migracioIdOrigen")
  private String migracioIdOrigen = null;

  @JsonProperty("motiuRelacio")
  private String motiuRelacio = null;

  @JsonProperty("nomProc")
  private String nomProc = null;

  @JsonProperty("nomSollicitant")
  private String nomSollicitant = null;

  @JsonProperty("nomUnitatOrganigrama")
  private String nomUnitatOrganigrama = null;

  @JsonProperty("numRegistre")
  private String numRegistre = null;

  @JsonProperty("pathSerieDoc")
  private String pathSerieDoc = null;

  @JsonProperty("serieDoc")
  private String serieDoc = null;

  @JsonProperty("tipusRegistre")
  private String tipusRegistre = null;

  @JsonProperty("titularRegistre")
  private String titularRegistre = null;

  public ExpedientGestorDocumentalRDTO codiExpRelacionat(String codiExpRelacionat) {
    this.codiExpRelacionat = codiExpRelacionat;
    return this;
  }

   /**
   * Get codiExpRelacionat
   * @return codiExpRelacionat
  **/
  @ApiModelProperty(value = "")
  public String getCodiExpRelacionat() {
    return codiExpRelacionat;
  }

  public void setCodiExpRelacionat(String codiExpRelacionat) {
    this.codiExpRelacionat = codiExpRelacionat;
  }

  public ExpedientGestorDocumentalRDTO codiExpedient(String codiExpedient) {
    this.codiExpedient = codiExpedient;
    return this;
  }

   /**
   * Get codiExpedient
   * @return codiExpedient
  **/
  @ApiModelProperty(value = "")
  public String getCodiExpedient() {
    return codiExpedient;
  }

  public void setCodiExpedient(String codiExpedient) {
    this.codiExpedient = codiExpedient;
  }

  public ExpedientGestorDocumentalRDTO codiLlargExpedient(String codiLlargExpedient) {
    this.codiLlargExpedient = codiLlargExpedient;
    return this;
  }

   /**
   * Get codiLlargExpedient
   * @return codiLlargExpedient
  **/
  @ApiModelProperty(value = "")
  public String getCodiLlargExpedient() {
    return codiLlargExpedient;
  }

  public void setCodiLlargExpedient(String codiLlargExpedient) {
    this.codiLlargExpedient = codiLlargExpedient;
  }

  public ExpedientGestorDocumentalRDTO codiUnitatOrganigrama(String codiUnitatOrganigrama) {
    this.codiUnitatOrganigrama = codiUnitatOrganigrama;
    return this;
  }

   /**
   * Get codiUnitatOrganigrama
   * @return codiUnitatOrganigrama
  **/
  @ApiModelProperty(value = "")
  public String getCodiUnitatOrganigrama() {
    return codiUnitatOrganigrama;
  }

  public void setCodiUnitatOrganigrama(String codiUnitatOrganigrama) {
    this.codiUnitatOrganigrama = codiUnitatOrganigrama;
  }

  public ExpedientGestorDocumentalRDTO cognom1Sollicitant(String cognom1Sollicitant) {
    this.cognom1Sollicitant = cognom1Sollicitant;
    return this;
  }

   /**
   * Get cognom1Sollicitant
   * @return cognom1Sollicitant
  **/
  @ApiModelProperty(value = "")
  public String getCognom1Sollicitant() {
    return cognom1Sollicitant;
  }

  public void setCognom1Sollicitant(String cognom1Sollicitant) {
    this.cognom1Sollicitant = cognom1Sollicitant;
  }

  public ExpedientGestorDocumentalRDTO cognom2Sollicitant(String cognom2Sollicitant) {
    this.cognom2Sollicitant = cognom2Sollicitant;
    return this;
  }

   /**
   * Get cognom2Sollicitant
   * @return cognom2Sollicitant
  **/
  @ApiModelProperty(value = "")
  public String getCognom2Sollicitant() {
    return cognom2Sollicitant;
  }

  public void setCognom2Sollicitant(String cognom2Sollicitant) {
    this.cognom2Sollicitant = cognom2Sollicitant;
  }

  public ExpedientGestorDocumentalRDTO dataRegistre(String dataRegistre) {
    this.dataRegistre = dataRegistre;
    return this;
  }

   /**
   * Get dataRegistre
   * @return dataRegistre
  **/
  @ApiModelProperty(value = "")
  public String getDataRegistre() {
    return dataRegistre;
  }

  public void setDataRegistre(String dataRegistre) {
    this.dataRegistre = dataRegistre;
  }

  public ExpedientGestorDocumentalRDTO descEstadoExp(String descEstadoExp) {
    this.descEstadoExp = descEstadoExp;
    return this;
  }

   /**
   * Get descEstadoExp
   * @return descEstadoExp
  **/
  @ApiModelProperty(value = "")
  public String getDescEstadoExp() {
    return descEstadoExp;
  }

  public void setDescEstadoExp(String descEstadoExp) {
    this.descEstadoExp = descEstadoExp;
  }

  public ExpedientGestorDocumentalRDTO destinatariRegistre(String destinatariRegistre) {
    this.destinatariRegistre = destinatariRegistre;
    return this;
  }

   /**
   * Get destinatariRegistre
   * @return destinatariRegistre
  **/
  @ApiModelProperty(value = "")
  public String getDestinatariRegistre() {
    return destinatariRegistre;
  }

  public void setDestinatariRegistre(String destinatariRegistre) {
    this.destinatariRegistre = destinatariRegistre;
  }

  public ExpedientGestorDocumentalRDTO documentErroni(String documentErroni) {
    this.documentErroni = documentErroni;
    return this;
  }

   /**
   * Get documentErroni
   * @return documentErroni
  **/
  @ApiModelProperty(value = "")
  public String getDocumentErroni() {
    return documentErroni;
  }

  public void setDocumentErroni(String documentErroni) {
    this.documentErroni = documentErroni;
  }

  public ExpedientGestorDocumentalRDTO documentIdentitatSollicitant(String documentIdentitatSollicitant) {
    this.documentIdentitatSollicitant = documentIdentitatSollicitant;
    return this;
  }

   /**
   * Get documentIdentitatSollicitant
   * @return documentIdentitatSollicitant
  **/
  @ApiModelProperty(value = "")
  public String getDocumentIdentitatSollicitant() {
    return documentIdentitatSollicitant;
  }

  public void setDocumentIdentitatSollicitant(String documentIdentitatSollicitant) {
    this.documentIdentitatSollicitant = documentIdentitatSollicitant;
  }

  public ExpedientGestorDocumentalRDTO documentacioIdext(BigDecimal documentacioIdext) {
    this.documentacioIdext = documentacioIdext;
    return this;
  }

   /**
   * Get documentacioIdext
   * @return documentacioIdext
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDocumentacioIdext() {
    return documentacioIdext;
  }

  public void setDocumentacioIdext(BigDecimal documentacioIdext) {
    this.documentacioIdext = documentacioIdext;
  }

  public ExpedientGestorDocumentalRDTO fechaFinExp(String fechaFinExp) {
    this.fechaFinExp = fechaFinExp;
    return this;
  }

   /**
   * Get fechaFinExp
   * @return fechaFinExp
  **/
  @ApiModelProperty(value = "")
  public String getFechaFinExp() {
    return fechaFinExp;
  }

  public void setFechaFinExp(String fechaFinExp) {
    this.fechaFinExp = fechaFinExp;
  }

  public ExpedientGestorDocumentalRDTO fechaIniExp(String fechaIniExp) {
    this.fechaIniExp = fechaIniExp;
    return this;
  }

   /**
   * Get fechaIniExp
   * @return fechaIniExp
  **/
  @ApiModelProperty(value = "")
  public String getFechaIniExp() {
    return fechaIniExp;
  }

  public void setFechaIniExp(String fechaIniExp) {
    this.fechaIniExp = fechaIniExp;
  }

  public ExpedientGestorDocumentalRDTO idEstat(BigDecimal idEstat) {
    this.idEstat = idEstat;
    return this;
  }

   /**
   * Get idEstat
   * @return idEstat
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getIdEstat() {
    return idEstat;
  }

  public void setIdEstat(BigDecimal idEstat) {
    this.idEstat = idEstat;
  }

  public ExpedientGestorDocumentalRDTO migracioIdOrigen(String migracioIdOrigen) {
    this.migracioIdOrigen = migracioIdOrigen;
    return this;
  }

   /**
   * Get migracioIdOrigen
   * @return migracioIdOrigen
  **/
  @ApiModelProperty(value = "")
  public String getMigracioIdOrigen() {
    return migracioIdOrigen;
  }

  public void setMigracioIdOrigen(String migracioIdOrigen) {
    this.migracioIdOrigen = migracioIdOrigen;
  }

  public ExpedientGestorDocumentalRDTO motiuRelacio(String motiuRelacio) {
    this.motiuRelacio = motiuRelacio;
    return this;
  }

   /**
   * Get motiuRelacio
   * @return motiuRelacio
  **/
  @ApiModelProperty(value = "")
  public String getMotiuRelacio() {
    return motiuRelacio;
  }

  public void setMotiuRelacio(String motiuRelacio) {
    this.motiuRelacio = motiuRelacio;
  }

  public ExpedientGestorDocumentalRDTO nomProc(String nomProc) {
    this.nomProc = nomProc;
    return this;
  }

   /**
   * Get nomProc
   * @return nomProc
  **/
  @ApiModelProperty(value = "")
  public String getNomProc() {
    return nomProc;
  }

  public void setNomProc(String nomProc) {
    this.nomProc = nomProc;
  }

  public ExpedientGestorDocumentalRDTO nomSollicitant(String nomSollicitant) {
    this.nomSollicitant = nomSollicitant;
    return this;
  }

   /**
   * Get nomSollicitant
   * @return nomSollicitant
  **/
  @ApiModelProperty(value = "")
  public String getNomSollicitant() {
    return nomSollicitant;
  }

  public void setNomSollicitant(String nomSollicitant) {
    this.nomSollicitant = nomSollicitant;
  }

  public ExpedientGestorDocumentalRDTO nomUnitatOrganigrama(String nomUnitatOrganigrama) {
    this.nomUnitatOrganigrama = nomUnitatOrganigrama;
    return this;
  }

   /**
   * Get nomUnitatOrganigrama
   * @return nomUnitatOrganigrama
  **/
  @ApiModelProperty(value = "")
  public String getNomUnitatOrganigrama() {
    return nomUnitatOrganigrama;
  }

  public void setNomUnitatOrganigrama(String nomUnitatOrganigrama) {
    this.nomUnitatOrganigrama = nomUnitatOrganigrama;
  }

  public ExpedientGestorDocumentalRDTO numRegistre(String numRegistre) {
    this.numRegistre = numRegistre;
    return this;
  }

   /**
   * Get numRegistre
   * @return numRegistre
  **/
  @ApiModelProperty(value = "")
  public String getNumRegistre() {
    return numRegistre;
  }

  public void setNumRegistre(String numRegistre) {
    this.numRegistre = numRegistre;
  }

  public ExpedientGestorDocumentalRDTO pathSerieDoc(String pathSerieDoc) {
    this.pathSerieDoc = pathSerieDoc;
    return this;
  }

   /**
   * Get pathSerieDoc
   * @return pathSerieDoc
  **/
  @ApiModelProperty(value = "")
  public String getPathSerieDoc() {
    return pathSerieDoc;
  }

  public void setPathSerieDoc(String pathSerieDoc) {
    this.pathSerieDoc = pathSerieDoc;
  }

  public ExpedientGestorDocumentalRDTO serieDoc(String serieDoc) {
    this.serieDoc = serieDoc;
    return this;
  }

   /**
   * Get serieDoc
   * @return serieDoc
  **/
  @ApiModelProperty(value = "")
  public String getSerieDoc() {
    return serieDoc;
  }

  public void setSerieDoc(String serieDoc) {
    this.serieDoc = serieDoc;
  }

  public ExpedientGestorDocumentalRDTO tipusRegistre(String tipusRegistre) {
    this.tipusRegistre = tipusRegistre;
    return this;
  }

   /**
   * Get tipusRegistre
   * @return tipusRegistre
  **/
  @ApiModelProperty(value = "")
  public String getTipusRegistre() {
    return tipusRegistre;
  }

  public void setTipusRegistre(String tipusRegistre) {
    this.tipusRegistre = tipusRegistre;
  }

  public ExpedientGestorDocumentalRDTO titularRegistre(String titularRegistre) {
    this.titularRegistre = titularRegistre;
    return this;
  }

   /**
   * Get titularRegistre
   * @return titularRegistre
  **/
  @ApiModelProperty(value = "")
  public String getTitularRegistre() {
    return titularRegistre;
  }

  public void setTitularRegistre(String titularRegistre) {
    this.titularRegistre = titularRegistre;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpedientGestorDocumentalRDTO expedientGestorDocumentalRDTO = (ExpedientGestorDocumentalRDTO) o;
    return Objects.equals(this.codiExpRelacionat, expedientGestorDocumentalRDTO.codiExpRelacionat) &&
        Objects.equals(this.codiExpedient, expedientGestorDocumentalRDTO.codiExpedient) &&
        Objects.equals(this.codiLlargExpedient, expedientGestorDocumentalRDTO.codiLlargExpedient) &&
        Objects.equals(this.codiUnitatOrganigrama, expedientGestorDocumentalRDTO.codiUnitatOrganigrama) &&
        Objects.equals(this.cognom1Sollicitant, expedientGestorDocumentalRDTO.cognom1Sollicitant) &&
        Objects.equals(this.cognom2Sollicitant, expedientGestorDocumentalRDTO.cognom2Sollicitant) &&
        Objects.equals(this.dataRegistre, expedientGestorDocumentalRDTO.dataRegistre) &&
        Objects.equals(this.descEstadoExp, expedientGestorDocumentalRDTO.descEstadoExp) &&
        Objects.equals(this.destinatariRegistre, expedientGestorDocumentalRDTO.destinatariRegistre) &&
        Objects.equals(this.documentErroni, expedientGestorDocumentalRDTO.documentErroni) &&
        Objects.equals(this.documentIdentitatSollicitant, expedientGestorDocumentalRDTO.documentIdentitatSollicitant) &&
        Objects.equals(this.documentacioIdext, expedientGestorDocumentalRDTO.documentacioIdext) &&
        Objects.equals(this.fechaFinExp, expedientGestorDocumentalRDTO.fechaFinExp) &&
        Objects.equals(this.fechaIniExp, expedientGestorDocumentalRDTO.fechaIniExp) &&
        Objects.equals(this.idEstat, expedientGestorDocumentalRDTO.idEstat) &&
        Objects.equals(this.migracioIdOrigen, expedientGestorDocumentalRDTO.migracioIdOrigen) &&
        Objects.equals(this.motiuRelacio, expedientGestorDocumentalRDTO.motiuRelacio) &&
        Objects.equals(this.nomProc, expedientGestorDocumentalRDTO.nomProc) &&
        Objects.equals(this.nomSollicitant, expedientGestorDocumentalRDTO.nomSollicitant) &&
        Objects.equals(this.nomUnitatOrganigrama, expedientGestorDocumentalRDTO.nomUnitatOrganigrama) &&
        Objects.equals(this.numRegistre, expedientGestorDocumentalRDTO.numRegistre) &&
        Objects.equals(this.pathSerieDoc, expedientGestorDocumentalRDTO.pathSerieDoc) &&
        Objects.equals(this.serieDoc, expedientGestorDocumentalRDTO.serieDoc) &&
        Objects.equals(this.tipusRegistre, expedientGestorDocumentalRDTO.tipusRegistre) &&
        Objects.equals(this.titularRegistre, expedientGestorDocumentalRDTO.titularRegistre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiExpRelacionat, codiExpedient, codiLlargExpedient, codiUnitatOrganigrama, cognom1Sollicitant, cognom2Sollicitant, dataRegistre, descEstadoExp, destinatariRegistre, documentErroni, documentIdentitatSollicitant, documentacioIdext, fechaFinExp, fechaIniExp, idEstat, migracioIdOrigen, motiuRelacio, nomProc, nomSollicitant, nomUnitatOrganigrama, numRegistre, pathSerieDoc, serieDoc, tipusRegistre, titularRegistre);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpedientGestorDocumentalRDTO {\n");
    
    sb.append("    codiExpRelacionat: ").append(toIndentedString(codiExpRelacionat)).append("\n");
    sb.append("    codiExpedient: ").append(toIndentedString(codiExpedient)).append("\n");
    sb.append("    codiLlargExpedient: ").append(toIndentedString(codiLlargExpedient)).append("\n");
    sb.append("    codiUnitatOrganigrama: ").append(toIndentedString(codiUnitatOrganigrama)).append("\n");
    sb.append("    cognom1Sollicitant: ").append(toIndentedString(cognom1Sollicitant)).append("\n");
    sb.append("    cognom2Sollicitant: ").append(toIndentedString(cognom2Sollicitant)).append("\n");
    sb.append("    dataRegistre: ").append(toIndentedString(dataRegistre)).append("\n");
    sb.append("    descEstadoExp: ").append(toIndentedString(descEstadoExp)).append("\n");
    sb.append("    destinatariRegistre: ").append(toIndentedString(destinatariRegistre)).append("\n");
    sb.append("    documentErroni: ").append(toIndentedString(documentErroni)).append("\n");
    sb.append("    documentIdentitatSollicitant: ").append(toIndentedString(documentIdentitatSollicitant)).append("\n");
    sb.append("    documentacioIdext: ").append(toIndentedString(documentacioIdext)).append("\n");
    sb.append("    fechaFinExp: ").append(toIndentedString(fechaFinExp)).append("\n");
    sb.append("    fechaIniExp: ").append(toIndentedString(fechaIniExp)).append("\n");
    sb.append("    idEstat: ").append(toIndentedString(idEstat)).append("\n");
    sb.append("    migracioIdOrigen: ").append(toIndentedString(migracioIdOrigen)).append("\n");
    sb.append("    motiuRelacio: ").append(toIndentedString(motiuRelacio)).append("\n");
    sb.append("    nomProc: ").append(toIndentedString(nomProc)).append("\n");
    sb.append("    nomSollicitant: ").append(toIndentedString(nomSollicitant)).append("\n");
    sb.append("    nomUnitatOrganigrama: ").append(toIndentedString(nomUnitatOrganigrama)).append("\n");
    sb.append("    numRegistre: ").append(toIndentedString(numRegistre)).append("\n");
    sb.append("    pathSerieDoc: ").append(toIndentedString(pathSerieDoc)).append("\n");
    sb.append("    serieDoc: ").append(toIndentedString(serieDoc)).append("\n");
    sb.append("    tipusRegistre: ").append(toIndentedString(tipusRegistre)).append("\n");
    sb.append("    titularRegistre: ").append(toIndentedString(titularRegistre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

