
/* Create Tables */
CREATE TABLE  "AUDIT_SERVEIS_PORTAL"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_TRAMITADORS"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_NOTIFICACIONS"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_PORTASIGNATURES"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_MDS"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_PORTAL_SOLL"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);

CREATE TABLE  "AUDIT_SERVEIS_SIGNATURES"
(
	"ID" NUMBER(19),
	"MOMENT_EXECUCIO" TIMESTAMP(6),
	"USUARI" NVARCHAR2(100),
	"DADES_AUTH" CLOB,
	"DADES_ENTRADA" CLOB,
	"DADES_RESPOSTA" CLOB,
	"MAPPING_ACCIO" NVARCHAR2(250),
	"VALUE_ACCIO" NVARCHAR2(250),
	"TIPUS_PETICIO" NVARCHAR2(6),
	"RESULTAT" NVARCHAR2(2),
	"DETALL_ERROR" CLOB
);


/* Create Sequences */
CREATE SEQUENCE "SERVEIS_PORTAL_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_TRAM_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_NOTIF_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_PORTASIG_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_MDS_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_PORT_SOLL_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE "SERVEIS_SIGNATURES_ID_SEQUENCE" INCREMENT BY 1 MINVALUE 1;



/* Create Primary Keys */
 
ALTER TABLE  "AUDIT_SERVEIS_PORTAL" ADD CONSTRAINT "PK_AUDIT_PORTAL_ID" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE  "AUDIT_SERVEIS_TRAMITADORS" ADD CONSTRAINT "PK_AUDIT_TRAMITADORS_ID" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE  "AUDIT_SERVEIS_NOTIFICACIONS" ADD CONSTRAINT "PK_AUDIT_NOTIFICACIONS_ID" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE  "AUDIT_SERVEIS_PORTASIGNATURES" ADD CONSTRAINT "PK_AUDIT_PORTASIGNATURES_ID" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE  "AUDIT_SERVEIS_MDS" ADD CONSTRAINT "PK_AUDIT_MDS_ID" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE  "AUDIT_SERVEIS_PORTAL_SOLL" ADD CONSTRAINT "PK_AUDIT_PORTAL_SOLL_ID" PRIMARY KEY ("ID") USING INDEX;
ALTER TABLE  "AUDIT_SERVEIS_SIGNATURES" ADD CONSTRAINT "PK_AUDIT_SIGNATURES_ID" PRIMARY KEY ("ID") USING INDEX;



/* Create Not Nulls */

ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("ID" CONSTRAINT "NN_ID_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTRADA_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESPOSTA_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PETICIO_AUDIT_PORTAL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_AUDIT_PORTAL" NOT NULL);

ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("ID" CONSTRAINT "NN_ID_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTRADA_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESPOSTA_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PETICIO_ADT_TRAM" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_TRAMITADORS" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_ADT_TRAM" NOT NULL);

ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("ID" CONSTRAINT "NN_ID_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTRADA_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESPOSTA_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PETICIO_ADT_NOTIF" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_NOTIFICACIONS" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_ADT_NOTIF" NOT NULL);

ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("ID" CONSTRAINT "NN_ID_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTRADA_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESPOSTA_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PETICIO_ADT_PORTASIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTASIGNATURES" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_ADT_PORTASIG" NOT NULL);

ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("ID" CONSTRAINT "NN_ID_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTRADA_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESPOSTA_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PETICIO_AUDIT_MDS" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_MDS" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_AUDIT_MDS" NOT NULL);


ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("ID" CONSTRAINT "NN_ID_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTR_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESP_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_AUD_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PET_AUDIT_PORT_SOL" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_PORTAL_SOLL" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_AUDIT_PORT_SOL" NOT NULL);



ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("ID" CONSTRAINT "NN_ID_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("MOMENT_EXECUCIO" CONSTRAINT "NN_MOM_EXECUCIO_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("USUARI" CONSTRAINT "NN_USUARI_AUDIT_SIGNATURES" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("DADES_AUTH" CONSTRAINT "NN_DADES_AUTH_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("DADES_ENTRADA" CONSTRAINT "NN_DADES_ENTRADA_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("DADES_RESPOSTA" CONSTRAINT "NN_DADES_RESPOSTA_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("MAPPING_ACCIO" CONSTRAINT "NN_MAPPING_ACCIO_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("VALUE_ACCIO" CONSTRAINT "NN_VALUE_ACCIO_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("TIPUS_PETICIO" CONSTRAINT "NN_TIPUS_PETICIO_AUDIT_SIG" NOT NULL);
ALTER TABLE "AUDIT_SERVEIS_SIGNATURES" MODIFY ("RESULTAT" CONSTRAINT "NN_RESULTAT_AUDIT_SIG" NOT NULL);



/* Create Foreign Keys */


/* Create Indexes */




CREATE OR REPLACE TRIGGER NLS_SETTINGS 

AFTER LOGON ON SCHEMA

  BEGIN
  
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_SORT=BINARY_AI';
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_COMP=LINGUISTIC';
    
  END NLS_SETTINGS;
  /


