/*
 * API gpaprocediments
 * API gpaprocediments
 *
 * OpenAPI spec version: 2.10.1
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpaprocediments;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaprocediments.ConfdocsentTramitsOvt;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaprocediments.ConfdocstramTramitsOvt;
import es.bcn.gpa.gpaserveis.rest.client.api.model.gpaprocediments.DadesOperTramitsOvt;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ReqOperatiusTramOvtRDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-11-08T16:49:56.830+01:00")
public class ReqOperatiusTramOvtRDTO {
  @JsonProperty("confDocEntrIdext")
  private BigDecimal confDocEntrIdext = null;

  @JsonProperty("confDocTramIdext")
  private BigDecimal confDocTramIdext = null;

  @JsonProperty("confdocsentTramitsOvtList")
  private List<ConfdocsentTramitsOvt> confdocsentTramitsOvtList = null;

  @JsonProperty("confdocstramTramitsOvtList")
  private List<ConfdocstramTramitsOvt> confdocstramTramitsOvtList = null;

  @JsonProperty("dadesOperVinculadesTramitList")
  private List<DadesOperTramitsOvt> dadesOperVinculadesTramitList = null;

  @JsonProperty("documentacioVinculada")
  private BigDecimal documentacioVinculada = null;

  @JsonProperty("editable")
  private Boolean editable = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("idReq")
  private BigDecimal idReq = null;

  @JsonProperty("identificadorRegistro")
  private String identificadorRegistro = null;

  @JsonProperty("identificadorTramit")
  private String identificadorTramit = null;

  @JsonProperty("nivellAutenticacio")
  private Integer nivellAutenticacio = null;

  @JsonProperty("nivellSignatura")
  private Integer nivellSignatura = null;

  @JsonProperty("representacioPuntual")
  private Integer representacioPuntual = null;

  @JsonProperty("seleccionable")
  private Boolean seleccionable = null;

  @JsonProperty("tramitGeneric")
  private Integer tramitGeneric = null;

  @JsonProperty("tramitOvtIdext")
  private BigDecimal tramitOvtIdext = null;

  @JsonProperty("tramitRegistre")
  private Integer tramitRegistre = null;

  @JsonProperty("tramitSignaturaCiutada")
  private Integer tramitSignaturaCiutada = null;

  public ReqOperatiusTramOvtRDTO confDocEntrIdext(BigDecimal confDocEntrIdext) {
    this.confDocEntrIdext = confDocEntrIdext;
    return this;
  }

   /**
   * Get confDocEntrIdext
   * @return confDocEntrIdext
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getConfDocEntrIdext() {
    return confDocEntrIdext;
  }

  public void setConfDocEntrIdext(BigDecimal confDocEntrIdext) {
    this.confDocEntrIdext = confDocEntrIdext;
  }

  public ReqOperatiusTramOvtRDTO confDocTramIdext(BigDecimal confDocTramIdext) {
    this.confDocTramIdext = confDocTramIdext;
    return this;
  }

   /**
   * Get confDocTramIdext
   * @return confDocTramIdext
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getConfDocTramIdext() {
    return confDocTramIdext;
  }

  public void setConfDocTramIdext(BigDecimal confDocTramIdext) {
    this.confDocTramIdext = confDocTramIdext;
  }

  public ReqOperatiusTramOvtRDTO confdocsentTramitsOvtList(List<ConfdocsentTramitsOvt> confdocsentTramitsOvtList) {
    this.confdocsentTramitsOvtList = confdocsentTramitsOvtList;
    return this;
  }

  public ReqOperatiusTramOvtRDTO addConfdocsentTramitsOvtListItem(ConfdocsentTramitsOvt confdocsentTramitsOvtListItem) {
    if (this.confdocsentTramitsOvtList == null) {
      this.confdocsentTramitsOvtList = new ArrayList<ConfdocsentTramitsOvt>();
    }
    this.confdocsentTramitsOvtList.add(confdocsentTramitsOvtListItem);
    return this;
  }

   /**
   * Get confdocsentTramitsOvtList
   * @return confdocsentTramitsOvtList
  **/
  @ApiModelProperty(value = "")
  public List<ConfdocsentTramitsOvt> getConfdocsentTramitsOvtList() {
    return confdocsentTramitsOvtList;
  }

  public void setConfdocsentTramitsOvtList(List<ConfdocsentTramitsOvt> confdocsentTramitsOvtList) {
    this.confdocsentTramitsOvtList = confdocsentTramitsOvtList;
  }

  public ReqOperatiusTramOvtRDTO confdocstramTramitsOvtList(List<ConfdocstramTramitsOvt> confdocstramTramitsOvtList) {
    this.confdocstramTramitsOvtList = confdocstramTramitsOvtList;
    return this;
  }

  public ReqOperatiusTramOvtRDTO addConfdocstramTramitsOvtListItem(ConfdocstramTramitsOvt confdocstramTramitsOvtListItem) {
    if (this.confdocstramTramitsOvtList == null) {
      this.confdocstramTramitsOvtList = new ArrayList<ConfdocstramTramitsOvt>();
    }
    this.confdocstramTramitsOvtList.add(confdocstramTramitsOvtListItem);
    return this;
  }

   /**
   * Get confdocstramTramitsOvtList
   * @return confdocstramTramitsOvtList
  **/
  @ApiModelProperty(value = "")
  public List<ConfdocstramTramitsOvt> getConfdocstramTramitsOvtList() {
    return confdocstramTramitsOvtList;
  }

  public void setConfdocstramTramitsOvtList(List<ConfdocstramTramitsOvt> confdocstramTramitsOvtList) {
    this.confdocstramTramitsOvtList = confdocstramTramitsOvtList;
  }

  public ReqOperatiusTramOvtRDTO dadesOperVinculadesTramitList(List<DadesOperTramitsOvt> dadesOperVinculadesTramitList) {
    this.dadesOperVinculadesTramitList = dadesOperVinculadesTramitList;
    return this;
  }

  public ReqOperatiusTramOvtRDTO addDadesOperVinculadesTramitListItem(DadesOperTramitsOvt dadesOperVinculadesTramitListItem) {
    if (this.dadesOperVinculadesTramitList == null) {
      this.dadesOperVinculadesTramitList = new ArrayList<DadesOperTramitsOvt>();
    }
    this.dadesOperVinculadesTramitList.add(dadesOperVinculadesTramitListItem);
    return this;
  }

   /**
   * Get dadesOperVinculadesTramitList
   * @return dadesOperVinculadesTramitList
  **/
  @ApiModelProperty(value = "")
  public List<DadesOperTramitsOvt> getDadesOperVinculadesTramitList() {
    return dadesOperVinculadesTramitList;
  }

  public void setDadesOperVinculadesTramitList(List<DadesOperTramitsOvt> dadesOperVinculadesTramitList) {
    this.dadesOperVinculadesTramitList = dadesOperVinculadesTramitList;
  }

  public ReqOperatiusTramOvtRDTO documentacioVinculada(BigDecimal documentacioVinculada) {
    this.documentacioVinculada = documentacioVinculada;
    return this;
  }

   /**
   * Get documentacioVinculada
   * @return documentacioVinculada
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDocumentacioVinculada() {
    return documentacioVinculada;
  }

  public void setDocumentacioVinculada(BigDecimal documentacioVinculada) {
    this.documentacioVinculada = documentacioVinculada;
  }

  public ReqOperatiusTramOvtRDTO editable(Boolean editable) {
    this.editable = editable;
    return this;
  }

   /**
   * Get editable
   * @return editable
  **/
  @ApiModelProperty(value = "")
  public Boolean isEditable() {
    return editable;
  }

  public void setEditable(Boolean editable) {
    this.editable = editable;
  }

  public ReqOperatiusTramOvtRDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ReqOperatiusTramOvtRDTO idReq(BigDecimal idReq) {
    this.idReq = idReq;
    return this;
  }

   /**
   * Get idReq
   * @return idReq
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getIdReq() {
    return idReq;
  }

  public void setIdReq(BigDecimal idReq) {
    this.idReq = idReq;
  }

  public ReqOperatiusTramOvtRDTO identificadorRegistro(String identificadorRegistro) {
    this.identificadorRegistro = identificadorRegistro;
    return this;
  }

   /**
   * Get identificadorRegistro
   * @return identificadorRegistro
  **/
  @ApiModelProperty(value = "")
  public String getIdentificadorRegistro() {
    return identificadorRegistro;
  }

  public void setIdentificadorRegistro(String identificadorRegistro) {
    this.identificadorRegistro = identificadorRegistro;
  }

  public ReqOperatiusTramOvtRDTO identificadorTramit(String identificadorTramit) {
    this.identificadorTramit = identificadorTramit;
    return this;
  }

   /**
   * Get identificadorTramit
   * @return identificadorTramit
  **/
  @ApiModelProperty(value = "")
  public String getIdentificadorTramit() {
    return identificadorTramit;
  }

  public void setIdentificadorTramit(String identificadorTramit) {
    this.identificadorTramit = identificadorTramit;
  }

  public ReqOperatiusTramOvtRDTO nivellAutenticacio(Integer nivellAutenticacio) {
    this.nivellAutenticacio = nivellAutenticacio;
    return this;
  }

   /**
   * Get nivellAutenticacio
   * @return nivellAutenticacio
  **/
  @ApiModelProperty(value = "")
  public Integer getNivellAutenticacio() {
    return nivellAutenticacio;
  }

  public void setNivellAutenticacio(Integer nivellAutenticacio) {
    this.nivellAutenticacio = nivellAutenticacio;
  }

  public ReqOperatiusTramOvtRDTO nivellSignatura(Integer nivellSignatura) {
    this.nivellSignatura = nivellSignatura;
    return this;
  }

   /**
   * Get nivellSignatura
   * @return nivellSignatura
  **/
  @ApiModelProperty(value = "")
  public Integer getNivellSignatura() {
    return nivellSignatura;
  }

  public void setNivellSignatura(Integer nivellSignatura) {
    this.nivellSignatura = nivellSignatura;
  }

  public ReqOperatiusTramOvtRDTO representacioPuntual(Integer representacioPuntual) {
    this.representacioPuntual = representacioPuntual;
    return this;
  }

   /**
   * Get representacioPuntual
   * @return representacioPuntual
  **/
  @ApiModelProperty(value = "")
  public Integer getRepresentacioPuntual() {
    return representacioPuntual;
  }

  public void setRepresentacioPuntual(Integer representacioPuntual) {
    this.representacioPuntual = representacioPuntual;
  }

  public ReqOperatiusTramOvtRDTO seleccionable(Boolean seleccionable) {
    this.seleccionable = seleccionable;
    return this;
  }

   /**
   * Get seleccionable
   * @return seleccionable
  **/
  @ApiModelProperty(value = "")
  public Boolean isSeleccionable() {
    return seleccionable;
  }

  public void setSeleccionable(Boolean seleccionable) {
    this.seleccionable = seleccionable;
  }

  public ReqOperatiusTramOvtRDTO tramitGeneric(Integer tramitGeneric) {
    this.tramitGeneric = tramitGeneric;
    return this;
  }

   /**
   * Get tramitGeneric
   * @return tramitGeneric
  **/
  @ApiModelProperty(value = "")
  public Integer getTramitGeneric() {
    return tramitGeneric;
  }

  public void setTramitGeneric(Integer tramitGeneric) {
    this.tramitGeneric = tramitGeneric;
  }

  public ReqOperatiusTramOvtRDTO tramitOvtIdext(BigDecimal tramitOvtIdext) {
    this.tramitOvtIdext = tramitOvtIdext;
    return this;
  }

   /**
   * Get tramitOvtIdext
   * @return tramitOvtIdext
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTramitOvtIdext() {
    return tramitOvtIdext;
  }

  public void setTramitOvtIdext(BigDecimal tramitOvtIdext) {
    this.tramitOvtIdext = tramitOvtIdext;
  }

  public ReqOperatiusTramOvtRDTO tramitRegistre(Integer tramitRegistre) {
    this.tramitRegistre = tramitRegistre;
    return this;
  }

   /**
   * Get tramitRegistre
   * @return tramitRegistre
  **/
  @ApiModelProperty(value = "")
  public Integer getTramitRegistre() {
    return tramitRegistre;
  }

  public void setTramitRegistre(Integer tramitRegistre) {
    this.tramitRegistre = tramitRegistre;
  }

  public ReqOperatiusTramOvtRDTO tramitSignaturaCiutada(Integer tramitSignaturaCiutada) {
    this.tramitSignaturaCiutada = tramitSignaturaCiutada;
    return this;
  }

   /**
   * Get tramitSignaturaCiutada
   * @return tramitSignaturaCiutada
  **/
  @ApiModelProperty(value = "")
  public Integer getTramitSignaturaCiutada() {
    return tramitSignaturaCiutada;
  }

  public void setTramitSignaturaCiutada(Integer tramitSignaturaCiutada) {
    this.tramitSignaturaCiutada = tramitSignaturaCiutada;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReqOperatiusTramOvtRDTO reqOperatiusTramOvtRDTO = (ReqOperatiusTramOvtRDTO) o;
    return Objects.equals(this.confDocEntrIdext, reqOperatiusTramOvtRDTO.confDocEntrIdext) &&
        Objects.equals(this.confDocTramIdext, reqOperatiusTramOvtRDTO.confDocTramIdext) &&
        Objects.equals(this.confdocsentTramitsOvtList, reqOperatiusTramOvtRDTO.confdocsentTramitsOvtList) &&
        Objects.equals(this.confdocstramTramitsOvtList, reqOperatiusTramOvtRDTO.confdocstramTramitsOvtList) &&
        Objects.equals(this.dadesOperVinculadesTramitList, reqOperatiusTramOvtRDTO.dadesOperVinculadesTramitList) &&
        Objects.equals(this.documentacioVinculada, reqOperatiusTramOvtRDTO.documentacioVinculada) &&
        Objects.equals(this.editable, reqOperatiusTramOvtRDTO.editable) &&
        Objects.equals(this.id, reqOperatiusTramOvtRDTO.id) &&
        Objects.equals(this.idReq, reqOperatiusTramOvtRDTO.idReq) &&
        Objects.equals(this.identificadorRegistro, reqOperatiusTramOvtRDTO.identificadorRegistro) &&
        Objects.equals(this.identificadorTramit, reqOperatiusTramOvtRDTO.identificadorTramit) &&
        Objects.equals(this.nivellAutenticacio, reqOperatiusTramOvtRDTO.nivellAutenticacio) &&
        Objects.equals(this.nivellSignatura, reqOperatiusTramOvtRDTO.nivellSignatura) &&
        Objects.equals(this.representacioPuntual, reqOperatiusTramOvtRDTO.representacioPuntual) &&
        Objects.equals(this.seleccionable, reqOperatiusTramOvtRDTO.seleccionable) &&
        Objects.equals(this.tramitGeneric, reqOperatiusTramOvtRDTO.tramitGeneric) &&
        Objects.equals(this.tramitOvtIdext, reqOperatiusTramOvtRDTO.tramitOvtIdext) &&
        Objects.equals(this.tramitRegistre, reqOperatiusTramOvtRDTO.tramitRegistre) &&
        Objects.equals(this.tramitSignaturaCiutada, reqOperatiusTramOvtRDTO.tramitSignaturaCiutada);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confDocEntrIdext, confDocTramIdext, confdocsentTramitsOvtList, confdocstramTramitsOvtList, dadesOperVinculadesTramitList, documentacioVinculada, editable, id, idReq, identificadorRegistro, identificadorTramit, nivellAutenticacio, nivellSignatura, representacioPuntual, seleccionable, tramitGeneric, tramitOvtIdext, tramitRegistre, tramitSignaturaCiutada);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReqOperatiusTramOvtRDTO {\n");
    
    sb.append("    confDocEntrIdext: ").append(toIndentedString(confDocEntrIdext)).append("\n");
    sb.append("    confDocTramIdext: ").append(toIndentedString(confDocTramIdext)).append("\n");
    sb.append("    confdocsentTramitsOvtList: ").append(toIndentedString(confdocsentTramitsOvtList)).append("\n");
    sb.append("    confdocstramTramitsOvtList: ").append(toIndentedString(confdocstramTramitsOvtList)).append("\n");
    sb.append("    dadesOperVinculadesTramitList: ").append(toIndentedString(dadesOperVinculadesTramitList)).append("\n");
    sb.append("    documentacioVinculada: ").append(toIndentedString(documentacioVinculada)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idReq: ").append(toIndentedString(idReq)).append("\n");
    sb.append("    identificadorRegistro: ").append(toIndentedString(identificadorRegistro)).append("\n");
    sb.append("    identificadorTramit: ").append(toIndentedString(identificadorTramit)).append("\n");
    sb.append("    nivellAutenticacio: ").append(toIndentedString(nivellAutenticacio)).append("\n");
    sb.append("    nivellSignatura: ").append(toIndentedString(nivellSignatura)).append("\n");
    sb.append("    representacioPuntual: ").append(toIndentedString(representacioPuntual)).append("\n");
    sb.append("    seleccionable: ").append(toIndentedString(seleccionable)).append("\n");
    sb.append("    tramitGeneric: ").append(toIndentedString(tramitGeneric)).append("\n");
    sb.append("    tramitOvtIdext: ").append(toIndentedString(tramitOvtIdext)).append("\n");
    sb.append("    tramitRegistre: ").append(toIndentedString(tramitRegistre)).append("\n");
    sb.append("    tramitSignaturaCiutada: ").append(toIndentedString(tramitSignaturaCiutada)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

