/*
 * API gpaprocediments
 * API gpaprocediments
 *
 * OpenAPI spec version: 1.28.1
 * Contact: sergio.corras@iecisa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.bcn.gpa.gpaserveis.rest.client.api.model.gpaprocediments;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * ReqOperatiusTramOvt
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-17T16:35:50.063+01:00")
public class ReqOperatiusTramOvt {
  @JsonProperty("idReq")
  private BigDecimal idReq = null;

  @JsonProperty("identificadorRegistro")
  private String identificadorRegistro = null;

  @JsonProperty("identificadorTramit")
  private String identificadorTramit = null;

  @JsonProperty("nivellAutenticacio")
  private Integer nivellAutenticacio = null;

  @JsonProperty("nivellSignatura")
  private Integer nivellSignatura = null;

  @JsonProperty("tramitGeneric")
  private Integer tramitGeneric = null;

  @JsonProperty("tramitOvtIdext")
  private BigDecimal tramitOvtIdext = null;

  public ReqOperatiusTramOvt idReq(BigDecimal idReq) {
    this.idReq = idReq;
    return this;
  }

   /**
   * Get idReq
   * @return idReq
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getIdReq() {
    return idReq;
  }

  public void setIdReq(BigDecimal idReq) {
    this.idReq = idReq;
  }

  public ReqOperatiusTramOvt identificadorRegistro(String identificadorRegistro) {
    this.identificadorRegistro = identificadorRegistro;
    return this;
  }

   /**
   * Get identificadorRegistro
   * @return identificadorRegistro
  **/
  @ApiModelProperty(value = "")
  public String getIdentificadorRegistro() {
    return identificadorRegistro;
  }

  public void setIdentificadorRegistro(String identificadorRegistro) {
    this.identificadorRegistro = identificadorRegistro;
  }

  public ReqOperatiusTramOvt identificadorTramit(String identificadorTramit) {
    this.identificadorTramit = identificadorTramit;
    return this;
  }

   /**
   * Get identificadorTramit
   * @return identificadorTramit
  **/
  @ApiModelProperty(value = "")
  public String getIdentificadorTramit() {
    return identificadorTramit;
  }

  public void setIdentificadorTramit(String identificadorTramit) {
    this.identificadorTramit = identificadorTramit;
  }

  public ReqOperatiusTramOvt nivellAutenticacio(Integer nivellAutenticacio) {
    this.nivellAutenticacio = nivellAutenticacio;
    return this;
  }

   /**
   * Get nivellAutenticacio
   * @return nivellAutenticacio
  **/
  @ApiModelProperty(value = "")
  public Integer getNivellAutenticacio() {
    return nivellAutenticacio;
  }

  public void setNivellAutenticacio(Integer nivellAutenticacio) {
    this.nivellAutenticacio = nivellAutenticacio;
  }

  public ReqOperatiusTramOvt nivellSignatura(Integer nivellSignatura) {
    this.nivellSignatura = nivellSignatura;
    return this;
  }

   /**
   * Get nivellSignatura
   * @return nivellSignatura
  **/
  @ApiModelProperty(value = "")
  public Integer getNivellSignatura() {
    return nivellSignatura;
  }

  public void setNivellSignatura(Integer nivellSignatura) {
    this.nivellSignatura = nivellSignatura;
  }

  public ReqOperatiusTramOvt tramitGeneric(Integer tramitGeneric) {
    this.tramitGeneric = tramitGeneric;
    return this;
  }

   /**
   * Get tramitGeneric
   * @return tramitGeneric
  **/
  @ApiModelProperty(value = "")
  public Integer getTramitGeneric() {
    return tramitGeneric;
  }

  public void setTramitGeneric(Integer tramitGeneric) {
    this.tramitGeneric = tramitGeneric;
  }

  public ReqOperatiusTramOvt tramitOvtIdext(BigDecimal tramitOvtIdext) {
    this.tramitOvtIdext = tramitOvtIdext;
    return this;
  }

   /**
   * Get tramitOvtIdext
   * @return tramitOvtIdext
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTramitOvtIdext() {
    return tramitOvtIdext;
  }

  public void setTramitOvtIdext(BigDecimal tramitOvtIdext) {
    this.tramitOvtIdext = tramitOvtIdext;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReqOperatiusTramOvt reqOperatiusTramOvt = (ReqOperatiusTramOvt) o;
    return Objects.equals(this.idReq, reqOperatiusTramOvt.idReq) &&
        Objects.equals(this.identificadorRegistro, reqOperatiusTramOvt.identificadorRegistro) &&
        Objects.equals(this.identificadorTramit, reqOperatiusTramOvt.identificadorTramit) &&
        Objects.equals(this.nivellAutenticacio, reqOperatiusTramOvt.nivellAutenticacio) &&
        Objects.equals(this.nivellSignatura, reqOperatiusTramOvt.nivellSignatura) &&
        Objects.equals(this.tramitGeneric, reqOperatiusTramOvt.tramitGeneric) &&
        Objects.equals(this.tramitOvtIdext, reqOperatiusTramOvt.tramitOvtIdext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idReq, identificadorRegistro, identificadorTramit, nivellAutenticacio, nivellSignatura, tramitGeneric, tramitOvtIdext);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReqOperatiusTramOvt {\n");
    
    sb.append("    idReq: ").append(toIndentedString(idReq)).append("\n");
    sb.append("    identificadorRegistro: ").append(toIndentedString(identificadorRegistro)).append("\n");
    sb.append("    identificadorTramit: ").append(toIndentedString(identificadorTramit)).append("\n");
    sb.append("    nivellAutenticacio: ").append(toIndentedString(nivellAutenticacio)).append("\n");
    sb.append("    nivellSignatura: ").append(toIndentedString(nivellSignatura)).append("\n");
    sb.append("    tramitGeneric: ").append(toIndentedString(tramitGeneric)).append("\n");
    sb.append("    tramitOvtIdext: ").append(toIndentedString(tramitOvtIdext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

